(define (problem London-Attack-Problem)
(:domain London-Attack-Domain)
(:objects

	Police-Car-A Police-Car-B Police-Car-C Police-Car-D Police-Car-E Police-Car-F - police-car
	Ambulance-A Ambulance-B Ambulance-C Ambulance-D - ambulance
	British-Transport-Police-Station Kennington-Police-Station Wood-Street-Police-Station - locatable
	Kings-College-Hospital St-Thomas-Hospital - locatable
	Casualty-A Casualty-B Casualty-C Casualty-D Casualty-E - casualty

	One Two Three Four Five Six Seven Eight Nine Ten
	Eleven Twelve Thirteen Fourteen Fifteen Sixteen Seventeen Eighteen Nineteen Twenty
	Twenty-One Twenty-Two Twenty-Three Twenty-Four Twenty-Five Twenty-Six Twenty-Seven Twenty-Eight Twenty-Nine Thirty
	Thirty-One Thirty-Two Thirty-Three Thirty-Four Thirty-Five Thirty-Six Thirty-Seven Thirty-Eight Thirty-Nine Forty
	Forty-One Forty-Two Forty-Three Forty-Four Forty-Five Forty-Six Forty-Seven Forty-Eight Forty-Nine Fifty 
	Fifty-One Fifty-Two Fifty-Three Fifty-Four Fifty-Five Fifty-Six Fifty-Seven Fifty-Eight Fifty-Nine Sixty
	Sixty-One Sixty-Two Sixty-Three Sixty-Four Sixty-Five Sixty-Six Sixty-Seven Sixty-Eight Sixty-Nine Seventy
	Seventy-One Seventy-Two Seventy-Three Seventy-Four Seventy-Five Seventy-Six Seventy-Seven Seventy-Eight Seventy-Nine Eighty
	Eighty-One Eighty-Two Eighty-Three Eighty-Four Eighty-Five Eighty-Six Eighty-Seven Eighty-Eight Eighty-Nine Ninety
	Ninety-One Ninety-Two Ninety-Three Ninety-Four Ninety-Five Ninety-Six Ninety-Seven Ninety-Eight Ninety-Nine One-Hundred

	One-Hundred-and-One One-Hundred-and-Two One-Hundred-and-Three One-Hundred-and-Four One-Hundred-and-Five One-Hundred-and-Six One-Hundred-and-Seven One-Hundred-and-Eight One-Hundred-and-Nine One-Hundred-and-Ten
	One-Hundred-and-Eleven One-Hundred-and-Twelve One-Hundred-and-Thirteen One-Hundred-and-Fourteen One-Hundred-and-Fifteen One-Hundred-and-Sixteen One-Hundred-and-Seventeen One-Hundred-and-Eighteen One-Hundred-and-Nineteen One-Hundred-and-Twenty
	One-Hundred-and-Twenty-One One-Hundred-and-Twenty-Two One-Hundred-and-Twenty-Three One-Hundred-and-Twenty-Four One-Hundred-and-Twenty-Five One-Hundred-and-Twenty-Six One-Hundred-and-Twenty-Seven One-Hundred-and-Twenty-Eight One-Hundred-and-Twenty-Nine One-Hundred-and-Thirty
	One-Hundred-and-Thirty-One One-Hundred-and-Thirty-Two One-Hundred-and-Thirty-Three One-Hundred-and-Thirty-Four One-Hundred-and-Thirty-Five One-Hundred-and-Thirty-Six One-Hundred-and-Thirty-Seven One-Hundred-and-Thirty-Eight One-Hundred-and-Thirty-Nine One-Hundred-and-Forty
	One-Hundred-and-Forty-One One-Hundred-and-Forty-Two One-Hundred-and-Forty-Three One-Hundred-and-Forty-Four One-Hundred-and-Forty-Five One-Hundred-and-Forty-Six One-Hundred-and-Forty-Seven One-Hundred-and-Forty-Eight One-Hundred-and-Forty-Nine One-Hundred-and-Fifty
	One-Hundred-and-Fifty-One One-Hundred-and-Fifty-Two One-Hundred-and-Fifty-Three One-Hundred-and-Fifty-Four One-Hundred-and-Fifty-Five One-Hundred-and-Fifty-Six One-Hundred-and-Fifty-Seven One-Hundred-and-Fifty-Eight One-Hundred-and-Fifty-Nine One-Hundred-and-Sixty
	One-Hundred-and-Sixty-One One-Hundred-and-Sixty-Two One-Hundred-and-Sixty-Three One-Hundred-and-Sixty-Four One-Hundred-and-Sixty-Five One-Hundred-and-Sixty-Six One-Hundred-and-Sixty-Seven One-Hundred-and-Sixty-Eight One-Hundred-and-Sixty-Nine One-Hundred-and-Seventy
	One-Hundred-and-Seventy-One One-Hundred-and-Seventy-Two One-Hundred-and-Seventy-Three One-Hundred-and-Seventy-Four One-Hundred-and-Seventy-Five One-Hundred-and-Seventy-Six One-Hundred-and-Seventy-Seven One-Hundred-and-Seventy-Eight One-Hundred-and-Seventy-Nine One-Hundred-and-Eighty
	One-Hundred-and-Eighty-One One-Hundred-and-Eighty-Two One-Hundred-and-Eighty-Three One-Hundred-and-Eighty-Four One-Hundred-and-Eighty-Five One-Hundred-and-Eighty-Six One-Hundred-and-Eighty-Seven One-Hundred-and-Eighty-Eight One-Hundred-and-Eighty-Nine One-Hundred-and-Ninety
	One-Hundred-and-Ninety-One One-Hundred-and-Ninety-Two One-Hundred-and-Ninety-Three One-Hundred-and-Ninety-Four One-Hundred-and-Ninety-Five One-Hundred-and-Ninety-Six One-Hundred-and-Ninety-Seven One-Hundred-and-Ninety-Eight One-Hundred-and-Ninety-Nine Two-Hundred
	
	Two-Hundred-and-One Two-Hundred-and-Two Two-Hundred-and-Three Two-Hundred-and-Four Two-Hundred-and-Five Two-Hundred-and-Six Two-Hundred-and-Seven Two-Hundred-and-Eight Two-Hundred-and-Nine Two-Hundred-and-Ten
	Two-Hundred-and-Eleven Two-Hundred-and-Twelve Two-Hundred-and-Thirteen Two-Hundred-and-Fourteen Two-Hundred-and-Fifteen Two-Hundred-and-Sixteen Two-Hundred-and-Seventeen Two-Hundred-and-Eighteen Two-Hundred-and-Nineteen Two-Hundred-and-Twenty
	Two-Hundred-and-Twenty-One Two-Hundred-and-Twenty-Two Two-Hundred-and-Twenty-Three Two-Hundred-and-Twenty-Four Two-Hundred-and-Twenty-Five Two-Hundred-and-Twenty-Six Two-Hundred-and-Twenty-Seven Two-Hundred-and-Twenty-Eight Two-Hundred-and-Twenty-Nine Two-Hundred-and-Thirty
	Two-Hundred-and-Thirty-One - location
		
)

(:init 

	(at British-Transport-Police-Station One-Hundred-and-Thirty-Seven)
	(at Kennington-Police-Station One-Hundred-and-Nine)
	(at Wood-Street-Police-Station One-Hundred-and-Sixty-Four)
	
	(at Kings-College-Hospital One-Hundred-and-Six)
	(at St-Thomas-Hospital Two-Hundred-and-Twenty-Two)
	
	(person-at Casualty-A Two-Hundred-and-Thirty)
	(person-at Casualty-B Two-Hundred-and-Thirty)
	(person-at Casualty-C Two-Hundred-and-Thirty)
	(person-at Casualty-D Two-Hundred-and-Thirty)
	(person-at Casualty-E Two-Hundred-and-Thirty)
	
	(vehicle-at Police-Car-A British-Transport-Police-Station)
	(vehicle-at Police-Car-B British-Transport-Police-Station)
	(vehicle-at Police-Car-C Kennington-Police-Station)
	(vehicle-at Police-Car-D Wood-Street-Police-Station)
	(vehicle-at Police-Car-E Nine)
	(vehicle-at Police-Car-F Twenty-Two)
	
	(vehicle-at Ambulance-A Twenty-Seven)
	(vehicle-at Ambulance-B Fourteen) 
	(vehicle-at Ambulance-C Five)
	(vehicle-at Ambulance-D Six)
	
	(available Ambulance-A)
	(available Ambulance-B)
	(available Ambulance-C)

	(linked One Forty-Three) 													(linked Forty-Three One)
	(linked Two Two-Hundred-and-Sixteen) 										(linked Two-Hundred-and-Sixteen Two)
	(linked Three Two-Hundred-and-Fifteen) 										(linked Two-Hundred-and-Fifteen Three)
	(linked Four Two-Hundred-and-Fourteen) 										(linked Two-Hundred-and-Fourteen Four)
	(linked Five Forty-Eight) 													(linked Forty-Eight Five)
	(linked Six Fifty-Three) 													(linked Fifty-Three Six)
	(linked Seven Fifty-Four) 													(linked Fifty-Four Seven)
	(linked Eight Fifty-Four) 													(linked Fifty-Four Eight)
	(linked Nine Two-Hundred-and-Eighteen) 										(linked Two-Hundred-and-Eighteen Nine)
	(linked Ten Two-Hundred-and-Eighteen) 										(linked Two-Hundred-and-Eighteen Ten)
	(linked Eleven Two-Hundred-and-Twenty) 										(linked Two-Hundred-and-Twenty Eleven)
	(linked Twelve Two-Hundred-and-Twenty-One) 									(linked Two-Hundred-and-Twenty-One Twelve)
	(linked Thirteen Two-Hundred-and-Twenty-One) 								(linked Two-Hundred-and-Twenty-One Thirteen)
	(linked Fourteen One-Hundred-and-Eleven) 									(linked One-Hundred-and-Eleven Fourteen)
	(linked Fifteen One-Hundred-and-Twelve) 									(linked One-Hundred-and-Twelve Fifteen)
	(linked Sixteen One-Hundred-and-Fifteen) 									(linked One-Hundred-and-Fifteen Sixteen)
	(linked Seventeen One-Hundred-and-Seventeen) 								(linked One-Hundred-and-Seventeen Seventeen)
	(linked Eighteen Two-Hundred-and-Twelve) 									(linked Two-Hundred-and-Twelve Eighteen)
	(linked Nineteen Two-Hundred-and-Six) 										(linked Two-Hundred-and-Six Nineteen)
	(linked Twenty Two-Hundred-and-Three) 										(linked Two-Hundred-and-Three Twenty)
	(linked Twenty-One Two-Hundred-and-Four) 									(linked Two-Hundred-and-Four Twenty-One)
	(linked Twenty-Two One-Hundred-and-Seventy-Eight) 							(linked One-Hundred-and-Seventy-Eight Twenty-One)
	(linked Twenty-Three One-Hundred-and-Seventy-Eight) 						(linked One-Hundred-and-Seventy-Eight Twenty-Three)
	(linked Twenty-Four Twenty-Five) 											(linked Twenty-Five Twenty-Four)
	(linked Twenty-Five One-Hundred-and-Seventy-Nine) 							(linked One-Hundred-and-Seventy-Nine Twenty-Five)
	(linked Twenty-Six One-Hundred-and-Eighty-Nine) 							(linked One-Hundred-and-Eighty-Nine Twenty-Six)
	(linked Twenty-Seven One-Hundred-and-Ninety) 								(linked One-Hundred-and-Ninety Twenty-Seven)
	(linked Twenty-Eight One-Hundred-and-Ninety) 								(linked One-Hundred-and-Ninety Twenty-Eight)
	(linked Twenty-Nine Two-Hundred-and-Twenty-Eight) 							(linked Two-Hundred-and-Twenty-Eight Twenty-Nine)
	(linked Thirty Two-Hundred-and-Twenty-Nine) 								(linked Two-Hundred-and-Twenty-Nine Thirty)
	(linked Thirty-One Two-Hundred-and-Twenty-Nine) 							(linked Two-Hundred-and-Twenty-Nine Thirty-One)
	(linked Thirty-Two One-Hundred-and-Ninety-One)								(linked One-Hundred-and-Ninety-One Thirty-Two)
	(linked Thirty-Three One-Hundred-and-Ninety-Seven) 							(linked One-Hundred-and-Ninety-Seven Thirty-Three)
	(linked Thirty-Four One-Hundred-and-Sixty-One) 								(linked One-Hundred-and-Sixty-One Thirty-Four)
	(linked Thirty-Five One-Hundred-and-Fifty-Seven) 							(linked One-Hundred-and-Fifty-Seven Thirty-Five)
	(linked Thirty-Six One-Hundred-and-Fifty-Seven) 							(linked One-Hundred-and-Fifty-Six Thirty-Seven)
	(linked Thirty-Seven One-Hundred-and-Fifty-Six) 							(linked One-Hundred-and-Fifty-Six Thirty-Seven)
	(linked Thirty-Eight One-Hundred-and-Fifty-Two) 							(linked One-Hundred-and-Fifty-Two Thirty-Eight)
	(linked Thirty-Nine One-Hundred-and-Forty-Six) 								(linked One-Hundred-and-Forty-Six Thirty-Nine)
	(linked Forty One-Hundred-and-Forty-Three) 									(linked One-Hundred-and-Forty-Three Forty)
	(linked Forty-One One-Hundred-and-Forty-Two) 								(linked One-Hundred-and-Forty-Two Forty-One)
	(linked Forty-Two Eighty) 													(linked Eighty Forty-Two) 						
	(linked Forty-Two Eighty-Two) 												(linked Eighty-Two Forty-Two)
	(linked Forty-Three Two-Hundred-and-Sixteen) 								(linked Two-Hundred-and-Sixteen Forty-Three) 
	(linked Forty-Three Seventy-Nine) 											(linked Seventy-Nine Forty-Three)
	(linked Forty-Four Two-Hundred-and-Fifteen) 								(linked Two-Hundred-and-Fifteen Forty-Four) 
	(linked Forty-Four Forty-Six) 												(linked Forty-Six Forty-Four) 
	(linked Forty-Four Seventy) 												(linked Seventy Forty-Four)
	(linked Forty-Four Seventy-Three) 											(linked Seventy-Three Forty-Four) 
	(linked Forty-Four Seventy-Six) 											(linked Seventy-Six Forty-Four)
	(linked Forty-Five Two-Hundred-and-Fourteen) 								(linked Two-Hundred-and-Fourteen Forty-Five) 
	(linked Forty-Five Forty-Six) 												(linked Forty-Six Forty-Five) 
	(linked Forty-Five Forty-Eight) 											(linked Forty-Eight Forty-Five)
	(linked Forty-Six Forty-Seven) 												(linked Forty-Seven Forty-Six)
	(linked Forty-Seven Forty-Nine) 											(linked Forty-Nine Forty-Seven) 
	(linked Forty-Seven Sixty-Nine) 											(linked Sixty-Nine Forty-Seven)
	(linked Forty-Eight Forty-Nine) 											(linked Forty-Nine Forty-Eight)
	(linked Forty-Nine Fifty) 													(linked Fifty Forty-Nine)
	(linked Forty-Nine Fifty-One) 												(linked Fifty-One Forty-Nine)
	(linked Fifty Sixty-Six) 													(linked Sixty-Six Fifty) 
	(linked Fifty Sixty-Eight)													(linked Sixty-Eight Fifty)
	(linked Fifty-One Fifty-Two) 												(linked Fifty-Two Fifty-One) 
	(linked Fifty-One Two-Hundred-and-Seventeen) 								(linked Two-Hundred-and-Seventeen Fifty-One)
	(linked Fifty-Two Fifty-Three) 												(linked Fifty-Three Fifty-Two) 
	(linked Fifty-Two Fifty-Five) 												(linked Fifty-Five Fifty-Two)
	(linked Fifty-Three Fifty-Four) 											(linked Fifty-Four Fifty-Three)
	(linked Fifty-Four Fifty-Five) 												(linked Fifty-Five Fifty-Four)
	(linked Fifty-Five Fifty-Six) 												(linked Fifty-Six Fifty-Five)
	(linked Fifty-Six Fifty-Seven) 												(linked Fifty-Seven Fifty-Six) 
	(linked Fifty-Six Two-Hundred-and-Eighteen) 								(linked Two-Hundred-and-Eighteen Fifty-Six)
	(linked Fifty-Seven Fifty-Eight) 											(linked Fifty-Eight Fifty-Seven) 
	(linked Fifty-Seven Two-Hundred-and-Seventeen) 								(linked Two-Hundred-and-Seventeen Fifty-Seven) 
	(linked Fifty-Seven Two-Hundred-and-Nineteen) 								(linked Two-Hundred-and-Nineteen Fifty-Seven)
	(linked Fifty-Eight Fifty-Nine) 											(linked Fifty-Nine Fifty-Eight) 
	(linked Fifty-Eight Sixty) 													(linked Sixty Fifty-Eight)
	(linked Fifty-Nine Sixty-One) 												(linked Sixty-One Fifty-Nine) 
	(linked Fifty-Nine Sixty-Two) 												(linked Sixty-Two Fifty-Nine)
	(linked Sixty Sixty-One) 													(linked Sixty-One Sixty) 
	(linked Sixty Ninety-Nine) 													(linked Ninety-Nine Sixty) 
	(linked Sixty Two-Hundred-and-Twenty) 										(linked Two-Hundred-and-Twenty Sixty) 
	(linked Sixty Two-Hundred-and-Twenty-One) 									(linked Two-Hundred-and-Twenty-One Sixty)
	(linked Sixty-One Sixty-Three) 												(linked Sixty-Three Sixty-One) 
	(linked Sixty-One Two-Hundred-and-Thirty-One) 								(linked Two-Hundred-and-Thirty-One Sixty-One)
	(linked Sixty-Two Sixty-Four) 												(linked Sixty-Four Sixty-Two)
	(linked Sixty-Two Two-Hundred-and-Seventeen) 								(linked Two-Hundred-and-Seventeen Sixty-Two)
	(linked Sixty-Three Sixty-Four) 											(linked Sixty-Four Sixty-Three) 
	(linked Sixty-Three Ninety-Two) 											(linked Ninety-Two Sixty-Three)
	(linked Sixty-Four Sixty-Five) 												(linked Sixty-Five Sixty-Four)
	(linked Sixty-Five Sixty-Six) 												(linked Sixty-Six Sixty-Five) 
	(linked Sixty-Five Eighty-Eight) 											(linked Eighty-Eight Sixty-Five)
	(linked Sixty-Six Sixty-Seven) 												(linked Sixty-Seven Sixty-six)
	(linked Sixty-Seven Sixty-Eight) 											(linked Sixty-Eight Sixty-Seven)
	(linked Sixty-Seven Eighty-Five)											(linked Eighty-Five Sixty-Seven) 
	(linked Sixty-Seven Eighty-Eight) 											(linked Eighty-Eight Sixty-Seven)
	(linked Sixty-Eight Sixty-Nine) 											(linked Sixty-Nine Sixty-Eight)
	(linked Sixty-Nine Seventy) 												(linked Seventy Sixty-Nine)
	(linked Sixty-Nine Seventy-One) 											(linked Seventy-One Sixty-Nine)
	(linked Seventy Seventy-One) 												(linked Seventy-One Seventy)
	(linked Seventy-One Seventy-Two) 											(linked Seventy-Two Seventy-One)
	(linked Seventy-Two Seventy-Three) 											(linked Seventy-Three Seventy-Two)
	(linked Seventy-Two Seventy-Four) 											(linked Seventy-Four Seventy-Two)
	(linked Seventy-Three Seventy-Four) 										(linked Seventy-Four Seventy-Three)
	(linked Seventy-Four Seventy-Five) 											(linked Seventy-Five Seventy-Four) 
	(linked Seventy-Four Seventy-Six) 											(linked Seventy-Six Seventy-Four)
	(linked Seventy-Four Eighty-Four) 											(linked Eighty-Four Seventy-Four)
	
	(linked Seventy-Six Seventy-Seven) 											(linked Seventy-Seven Seventy-Six) 
	(linked Seventy-Six Seventy-Nine) 											(linked Seventy-Nine Seventy-Six)
	(linked Seventy-Seven Seventy-Eight) 										(linked Seventy-Eight Seventy-Seven)
	(linked Seventy-Seven Eighty-Two) 											(linked Eighty-Two Seventy-Seven)
	(linked Seventy-Seven Eighty-Four) 											(linked Eighty-Four Seventy-Seven)
	(linked Seventy-Eight Seventy-Nine) 										(linked Seventy-Nine Seventy-Eight) 
	(linked Seventy-Eight Eighty-One)									 		(linked Eighty-One Seventy-Eight)
	(linked Seventy-Nine Eighty) 												(linked Eighty Seventy-Nine) 
	(linked Eighty Eighty-One) 													(linked Eighty-One Eighty)
	
	(linked Eighty-Two Two-Hundred-and-Thirteen) 								(linked Two-Hundred-and-Thirteen Eighty-Two)
	(linked Eighty-Three Eighty-Four) 											(linked Eighty-Four Eighty-Three)
	(linked Eighty-Four Eighty-Five) 											(linked Eighty-Five Eighty-Four)
	(linked Eighty-Five Eighty-Six) 											(linked Eighty-Six Eighty-Five)
	(linked Eighty-Six Eighty-Seven) 											(linked Eighty-Seven Eighty-Six) 
	(linked Eighty-Six Two-Hundred-and-Thirteen) 								(linked Two-Hundred-and-Thirteen Eighty-Six)
	(linked Eighty-Seven Eighty-Nine) 											(linked Eighty-Nine Eighty-Seven)
	(linked Eighty-Seven One-Hundred-and-Forty) 								(linked One-Hundred-and-Forty Eighty-Seven)
	(linked Eighty-Eight Eighty-Nine) 											(linked Eighty-Nine Eighty-Eight)
	(linked Eighty-Nine Ninety) 												(linked Ninety Eighty-Nine)
	(linked Ninety Ninety-One) 													(linked Ninety-One Ninety) 
	(linked Ninety One-Hundred-and-Thirty-Seven) 								(linked One-Hundred-and-Thirty-Seven Ninety)
	(linked Ninety One-Hundred-and-Thirty-Nine) 								(linked One-Hundred-and-Thirty-Nine Ninety)
	(linked Ninety-One Ninety-Two) 												(linked Ninety-Two Ninety-One)
	(linked Ninety-One One-Hundred-and-Thirty-Six) 								(linked One-Hundred-and-Thirty-Six Ninety-One)
	(linked Ninety-Two Ninety-Three) 											(linked Ninety-Three Ninety-Two)
	(linked Ninety-Three Ninety-Four) 											(linked Ninety-Four Ninety-Three) 
	(linked Ninety-Three Ninety-Five) 											(linked Ninety-Five Ninety-Three)
	(linked Ninety-Four Ninety-Five) 											(linked Ninety-Five Ninety-Four) 
	(linked Ninety-Four One-Hundred-and-Twenty-Seven) 							(linked One-Hundred-and-Twenty-Seven Ninety-Four)
	(linked Ninety-Five Ninety-Six) 											(linked Ninety-Six Ninety-Five)
	(linked Ninety-Six Ninety-Seven) 											(linked Ninety-Seven Ninety-Six) 
	(linked Ninety-Six Two-Hundred-and-Twenty-Four) 							(linked Two-Hundred-and-Twenty-Four Ninety-Six)
	(linked Ninety-Seven Ninety-Eight) 											(linked Ninety-Eight Ninety-Seven) 
	(linked Ninety-Seven Two-Hundred-and-Thirty-One)							(linked Two-Hundred-and-Thirty-One Ninety-Seven)
	(linked Ninety-Eight Ninety-Nine) 											(linked Ninety-Nine Ninety-Eight) 
	(linked Ninety-Eight Two-Hundred-and-Thirty) 								(linked Two-Hundred-and-Thirty Ninety-Eight)
	(linked Ninety-Nine One-Hundred) 											(linked One-Hundred Ninety-Nine)
	(linked Ninety-Nine Two-Hundred-and-Thirty-One) 							(linked Two-Hundred-and-Thirty-One Ninety-Nine)
	(linked One-Hundred One-Hundred-and-One) 									(linked One-Hundred-and-One One-Hundred) 
	(linked One-Hundred Two-Hundred-and-Twenty-One) 							(linked Two-Hundred-and-Twenty-One One-Hundred)
	(linked One-Hundred-and-One One-Hundred-and-Two) 							(linked One-Hundred-and-Two One-Hundred-and-One) 
	(linked One-Hundred-and-One Two-Hundred-and-Thirty) 						(linked Two-Hundred-and-Thirty One-Hundred-and-One)
	(linked One-Hundred-and-Two One-Hundred-and-Three) 							(linked One-Hundred-and-Three One-Hundred-and-Two) 
	(linked One-Hundred-and-Two One-Hundred-and-Ten) 							(linked One-Hundred-and-Ten One-Hundred-and-Two)
	(linked One-Hundred-and-Two Two-Hundred-and-Twenty-Two) 					(linked Two-Hundred-and-Twenty-Two One-Hundred-and-Two)
	(linked One-Hundred-and-Three One-Hundred-and-Four) 						(linked One-Hundred-and-Four One-Hundred-and-Three) 
	(linked One-Hundred-and-Three Two-Hundred-and-Twenty-Two) 					(linked Two-Hundred-and-Twenty-Two One-Hundred-and-Three)
	(linked One-Hundred-and-Four One-Hundred-and-Five) 							(linked One-Hundred-and-Five One-Hundred-and-Four) 
	(linked One-Hundred-and-Four One-Hundred-and-Six) 							(linked One-Hundred-and-Six One-Hundred-and-Four)
	(linked One-Hundred-and-Four One-Hundred-and-Nine) 							(linked One-Hundred-and-Nine One-Hundred-and-Four)
	(linked One-Hundred-and-Five One-Hundred-and-Seven) 						(linked One-Hundred-and-Seven One-Hundred-and-Five)
	(linked One-Hundred-and-Five One-Hundred-and-Eight) 						(linked One-Hundred-and-Eight One-Hundred-and-Five)
	(linked One-Hundred-and-Five One-Hundred-and-Twenty-Five) 					(linked One-Hundred-and-Twenty-Five One-Hundred-and-Five)
	(linked One-Hundred-and-Six One-Hundred-and-Seven) 							(linked One-Hundred-and-Seven One-Hundred-and-Six) 
	(linked One-Hundred-and-Six Two-Hundred-and-Twenty-Three) 					(linked Two-Hundred-and-Twenty-Three One-Hundred-and-Six)
	(linked One-Hundred-and-Seven Two-Hundred-and-Twenty-Four) 					(linked Two-Hundred-and-Twenty-Four One-Hundred-and-Seven)
	(linked One-Hundred-and-Eight One-Hundred-and-Twenty-Seven) 				(linked One-Hundred-and-Twenty-Seven One-Hundred-and-Eight) 
	(linked One-Hundred-and-Eight One-Hundred-and-Twenty-Nine) 					(linked One-Hundred-and-Twenty-Nine One-Hundred-and-Eight)
	(linked One-Hundred-and-Nine One-Hundred-and-Ten) 							(linked One-Hundred-and-Ten One-Hundred-and-Nine)
	(linked One-Hundred-and-Nine One-Hundred-and-Twenty-Four) 					(linked One-Hundred-and-Twenty-Four One-Hundred-and-Nine)
	(linked One-Hundred-and-Ten One-Hundred-and-Eleven) 						(linked One-Hundred-and-Eleven One-Hundred-and-Ten) 
	(linked One-Hundred-and-Ten One-Hundred-and-Thirteen) 						(linked One-Hundred-and-Thirteen One-Hundred-and-Ten)
	(linked One-Hundred-and-Eleven One-Hundred-and-Twelve) 						(linked One-Hundred-and-Twelve One-Hundred-and-Eleven) 
	(linked One-Hundred-and-Twelve One-Hundred-and-Thirteen) 					(linked One-Hundred-and-Thirteen One-Hundred-and-Twelve)
	(linked One-Hundred-and-Thirteen One-Hundred-and-Fourteen) 					(linked One-Hundred-and-Fourteen One-Hundred-and-Thirteen)
	(linked One-Hundred-and-Fourteen One-Hundred-and-Fifteen) 					(linked One-Hundred-and-Fifteen One-Hundred-and-Fourteen) 
	(linked One-Hundred-and-Fourteen One-Hundred-and-Eighteen) 					(linked One-Hundred-and-Eighteen One-Hundred-and-Fourteen)
	(linked One-Hundred-and-Fifteen One-Hundred-and-Sixteen) 					(linked One-Hundred-and-Sixteen One-Hundred-and-Fifteen)
	(linked One-Hundred-and-Sixteen One-Hundred-and-Seventeen) 					(linked One-Hundred-and-Seventeen One-Hundred-and-Sixteen) 
	(linked One-Hundred-and-Sixteen One-Hundred-and-Nineteen) 					(linked One-Hundred-and-Nineteen One-Hundred-and-Sixteen)
	(linked One-Hundred-and-Seventeen Two-Hundred-and-Eleven) 					(linked Two-Hundred-and-Eleven One-Hundred-and-Seventeen)
	(linked One-Hundred-and-Eighteen One-Hundred-and-Nineteen) 					(linked One-Hundred-and-Nineteen One-Hundred-and-Eighteen) 
	(linked One-Hundred-and-Eighteen One-Hundred-and-Twenty-Four) 				(linked One-Hundred-and-Twenty-Four One-Hundred-and-Eighteen)
	(linked One-Hundred-and-Nineteen One-Hundred-and-Twenty) 					(linked One-Hundred-and-Twenty One-Hundred-and-Nineteen)
	(linked One-Hundred-and-Nineteen One-Hundred-and-Twenty-One) 				(linked One-Hundred-and-Twenty-One One-Hundred-and-Nineteen)
	(linked One-Hundred-and-Twenty One-Hundred-and-Ninety-Nine) 				(linked One-Hundred-and-Ninety-Nine One-Hundred-and-Twenty) 
	(linked One-Hundred-and-Twenty Two-Hundred-and-Ten) 						(linked Two-Hundred-and-Ten One-Hundred-and-Twenty)
	(linked One-Hundred-and-Twenty-One One-Hundred-and-Twenty-Two) 				(linked One-Hundred-and-Twenty-Two One-Hundred-and-Twenty-One) 
	(linked One-Hundred-and-Twenty-One One-Hundred-and-Ninety-Nine) 			(linked One-Hundred-and-Ninety-Nine One-Hundred-and-Twenty-One)
	(linked One-Hundred-and-Twenty-Two One-Hundred-and-Seventy-One) 			(linked One-Hundred-and-Seventy-One One-Hundred-and-Twenty-Two)
	(linked One-Hundred-and-Twenty-Two One-Hundred-and-Seventy-Two) 			(linked One-Hundred-and-Seventy-Two One-Hundred-and-Twenty-Two)
	(linked One-Hundred-and-Twenty-Three One-Hundred-and-Twenty-Six) 			(linked One-Hundred-and-Twenty-Six One-Hundred-and-Twenty-Three)
	(linked One-Hundred-and-Twenty-Four One-Hundred-and-Twenty-Five) 			(linked One-Hundred-and-Twenty-Five One-Hundred-and-Twenty-Four)
	(linked One-Hundred-and-Twenty-Five One-Hundred-and-Twenty-Six) 			(linked One-Hundred-and-Twenty-Six One-Hundred-and-Twenty-Five)
	(linked One-Hundred-and-Twenty-Six One-Hundred-and-Thirty-One) 				(linked One-Hundred-and-Thirty-One One-Hundred-and-Twenty-Six)
	(linked One-Hundred-and-Twenty-Six One-Hundred-and-Sixty-Seven) 			(linked One-Hundred-and-Sixty-Seven One-Hundred-and-Twenty-Six)
	(linked One-Hundred-and-Twenty-Seven One-Hundred-and-Twenty-Eight) 			(linked One-Hundred-and-Twenty-Eight One-Hundred-and-Twenty-Seven)
	(linked One-Hundred-and-Twenty-Seven One-Hundred-and-Thirty-Six) 			(linked One-Hundred-and-Thirty-Six One-Hundred-and-Twenty-Seven)
	(linked One-Hundred-and-Twenty-Eight One-Hundred-and-Twenty-Nine) 			(linked One-Hundred-and-Twenty-Nine One-Hundred-and-Twenty-Eight)
	(linked One-Hundred-and-Twenty-Eight One-Hundred-and-Thirty-Five) 			(linked One-Hundred-and-Thirty-Five One-Hundred-and-Twenty-Eight)
	(linked One-Hundred-and-Twenty-Nine One-Hundred-and-Thirty) 				(linked One-Hundred-and-Thirty One-Hundred-and-Twenty-Nine)
	(linked One-Hundred-and-Twenty-Nine One-Hundred-and-Thirty-Four) 			(linked One-Hundred-and-Thirty-Four One-Hundred-and-Twenty-Nine)
	(linked One-Hundred-and-Thirty One-Hundred-and-Thirty-One) 					(linked One-Hundred-and-Thirty-One One-Hundred-and-Thirty) 
	(linked One-Hundred-and-Thirty One-Hundred-and-Thirty-Three) 				(linked One-Hundred-and-Thirty-Three One-Hundred-and-Thirty)
	(linked One-Hundred-and-Thirty-One One-Hundred-and-Thirty-Two) 				(linked One-Hundred-and-Thirty-Two One-Hundred-and-Thirty-One)
	(linked One-Hundred-and-Thirty-One One-Hundred-and-Sixty-Four) 				(linked One-Hundred-and-Sixty-Four One-Hundred-and-Thirty-One)
	(linked One-Hundred-and-Thirty-One One-Hundred-and-Sixty-Six) 				(linked One-Hundred-and-Sixty-Six One-Hundred-and-Thirty-One)
	(linked One-Hundred-and-Thirty-Two One-Hundred-and-Thirty-Three) 			(linked One-Hundred-and-Thirty-Three One-Hundred-and-Thirty-Two)
	(linked One-Hundred-and-Thirty-Two One-Hundred-and-Sixty-Two) 				(linked One-Hundred-and-Sixty-Two One-Hundred-and-Thirty-Two)
	(linked One-Hundred-and-Thirty-Two Two-Hundred-and-Twenty-Seven) 			(linked Two-Hundred-and-Twenty-Seven One-Hundred-and-Thirty-Two)
	(linked One-Hundred-and-Thirty-Three One-Hundred-and-Thirty-Four) 			(linked One-Hundred-and-Thirty-Four One-Hundred-and-Thirty-Three)
	(linked One-Hundred-and-Thirty-Three One-Hundred-and-Forty-Nine) 			(linked One-Hundred-and-Forty-Nine One-Hundred-and-Thirty-Three)
	(linked One-Hundred-and-Thirty-Four One-Hundred-and-Thirty-Five) 			(linked One-Hundred-and-Thirty-Five One-Hundred-and-Thirty-Four)
	(linked One-Hundred-and-Thirty-Four One-Hundred-and-Fifty) 					(linked One-Hundred-and-Fifty One-Hundred-and-Thirty-Four)
	(linked One-Hundred-and-Thirty-Five One-Hundred-and-Thirty-Six) 			(linked One-Hundred-and-Thirty-Six One-Hundred-and-Thirty-Five)
	(linked One-Hundred-and-Thirty-Five One-Hundred-and-Fifty-One)  			(linked One-Hundred-and-Fifty-One One-Hundred-and-Thirty-Five)
	(linked One-Hundred-and-Thirty-Six One-Hundred-and-Thirty-Seven) 			(linked One-Hundred-and-Thirty-Seven One-Hundred-and-Thirty-Six)
	(linked One-Hundred-and-Thirty-Seven One-Hundred-and-Thirty-Eight) 			(linked One-Hundred-and-Thirty-Eight One-Hundred-and-Thirty-Seven)
	(linked One-Hundred-and-Thirty-Eight One-Hundred-and-Thirty-Nine) 			(linked One-Hundred-and-Thirty-Nine One-Hundred-and-Thirty-Eight)
	(linked One-Hundred-and-Thirty-Eight One-Hundred-and-Fifty-One) 			(linked One-Hundred-and-Fifty-One One-Hundred-and-Thirty-Eight)
	(linked One-Hundred-and-Thirty-Nine One-Hundred-and-Forty) 					(linked One-Hundred-and-Forty One-Hundred-and-Thirty-Nine)
	(linked One-Hundred-and-Forty One-Hundred-and-Forty-One) 					(linked One-Hundred-and-Forty-One One-Hundred-and-Forty)
	(linked One-Hundred-and-Forty-One Two-Hundred-and-Thirteen) 				(linked Two-Hundred-and-Thirteen One-Hundred-and-Forty-One)
	(linked One-Hundred-and-Forty-One Two-Hundred-and-Twenty-Nine) 				(linked Two-Hundred-and-Twenty-Nine One-Hundred-and-Forty-One)
	(linked One-Hundred-and-Forty-Two One-Hundred-and-Forty-Three) 				(linked One-Hundred-and-Forty-Three One-Hundred-and-Forty-Two)
	(linked One-Hundred-and-Forty-Two One-Hundred-and-Forty-One) 				(linked One-Hundred-and-Forty-One One-Hundred-and-Forty-Two)
	(linked One-Hundred-and-Forty-Two Two-Hundred-and-Twenty-Nine) 				(linked Two-Hundred-and-Twenty-Nine One-Hundred-and-Forty-Two)
	
		(linked One-Hundred-and-Forty-Three One-Hundred-and-Forty-Four) 	(linked One-Hundred-and-Forty-Four One-Hundred-and-Forty-Three)
	(linked One-Hundred-and-Forty-Four One-Hundred-and-Forty-Five) 		(linked One-Hundred-and-Forty-Five One-Hundred-and-Forty-Four)
	(linked One-Hundred-and-Forty-Four Two-Hundred-and-Twenty-Nine) 	(linked Two-Hundred-and-Twenty-Nine One-Hundred-and-Forty-Four)
	(linked One-Hundred-and-Forty-Five One-Hundred-and-Forty-Six) 		(linked One-Hundred-and-Forty-Six One-Hundred-and-Forty-Five)
	(linked One-Hundred-and-Forty-Five Two-Hundred-and-Twenty-Five) 	(linked Two-Hundred-and-Twenty-Five One-Hundred-and-Forty-Five)
	(linked One-Hundred-and-Forty-Six One-Hundred-and-Forty-Seven) 		(linked One-Hundred-and-Forty-Seven One-Hundred-and-Forty-Six)
	(linked One-Hundred-and-Forty-Seven One-Hundred-and-Forty-Nine) 	(linked One-Hundred-and-Forty-Nine One-Hundred-and-Forty-Seven)
	(linked One-Hundred-and-Forty-Seven Two-Hundred-and-Twenty-Five) 	(linked Two-Hundred-and-Twenty-Five One-Hundred-and-Forty-Seven)
	(linked One-Hundred-and-Forty-Eight One-Hundred-and-Forty-Nine) 	(linked One-Hundred-and-Forty-Nine One-Hundred-and-Forty-Eight) 
	(linked One-Hundred-and-Forty-Eight One-Hundred-and-Fifty) 			(linked One-Hundred-and-Fifty One-Hundred-and-Forty-Eight)
	(linked One-Hundred-and-Forty-Eight Two-Hundred-and-Twenty-Five) 	(linked Two-Hundred-and-Twenty-Five One-Hundred-and-Forty-Eight)
	(linked One-Hundred-and-Forty-Nine One-Hundred-and-Fifty-Two) 		(linked One-Hundred-and-Fifty-Two One-Hundred-and-Forty-Nine)
	(linked One-Hundred-and-Fifty One-Hundred-and-Fifty-One) 			(linked One-Hundred-and-Fifty-One One-Hundred-and-Fifty)
	(linked One-Hundred-and-Fifty-One Two-Hundred-and-Twenty-Five) 		(linked Two-Hundred-and-Twenty-Five One-Hundred-and-Fifty-One) 
	(linked One-Hundred-and-Fifty-One Two-Hundred-and-Twenty-Nine) 		(linked Two-Hundred-and-Twenty-Nine One-Hundred-and-Fifty-One)
	(linked One-Hundred-and-Fifty-Two Two-Hundred-and-Twenty-Seven) 	(linked Two-Hundred-and-Twenty-Seven One-Hundred-and-Fifty-Two)
	(linked One-Hundred-and-Fifty-Three One-Hundred-and-Fifty-Four) 	(linked One-Hundred-and-Fifty-Four One-Hundred-and-Fifty-Three)
	(linked One-Hundred-and-Fifty-Three One-Hundred-and-Fifty-Five) 	(linked One-Hundred-and-Fifty-Five One-Hundred-and-Fifty-Three)
	(linked One-Hundred-and-Fifty-Three Two-Hundred-and-Twenty-Seven) 	(linked Two-Hundred-and-Twenty-Seven One-Hundred-and-Fifty-Three)
	(linked One-Hundred-and-Fifty-Four One-Hundred-and-Fifty-Five) 		(linked One-Hundred-and-Fifty-Five One-Hundred-and-Fifty-Four)
	(linked One-Hundred-and-Fifty-Four One-Hundred-and-Sixty-Two) 		(linked One-Hundred-and-Sixty-Two One-Hundred-and-Fifty-Four)
	(linked One-Hundred-and-Fifty-Five One-Hundred-and-Fifty-Six) 		(linked One-Hundred-and-Fifty-Six One-Hundred-and-Fifty-Five)
	(linked One-Hundred-and-Fifty-Six One-Hundred-and-Fifty-Seven) 		(linked One-Hundred-and-Fifty-Seven One-Hundred-and-Fifty-Six)
	(linked One-Hundred-and-Fifty-Seven One-Hundred-and-Fifty-Eight) 	(linked One-Hundred-and-Fifty-Eight One-Hundred-and-Fifty-Seven)
	(linked One-Hundred-and-Fifty-Eight One-Hundred-and-Fifty-Nine) 	(linked One-Hundred-and-Fifty-Nine One-Hundred-and-Fifty-Eight)
	(linked One-Hundred-and-Fifty-Eight One-Hundred-and-Sixty) 			(linked One-Hundred-and-Sixty One-Hundred-and-Fifty-Eight)
	(linked One-Hundred-and-Fifty-Eight One-Hundred-and-Sixty-One) 		(linked One-Hundred-and-Sixty-One One-Hundred-and-Fifty-Eight)
	
	(linked One-Hundred-and-Sixty One-Hundred-and-Sixty-One) 			(linked One-Hundred-and-Sixty-One One-Hundred-and-Sixty)
	(linked One-Hundred-and-Sixty One-Hundred-and-Sixty-Three) 			(linked One-Hundred-and-Sixty-Three One-Hundred-and-Sixty)

	(linked One-Hundred-and-Sixty-Two One-Hundred-and-Sixty-Three) 		(linked One-Hundred-and-Sixty-Three One-Hundred-and-Sixty-Two)
	(linked One-Hundred-and-Sixty-Two One-Hundred-and-Sixty-Three) 		(linked One-Hundred-and-Sixty-Three One-Hundred-and-Sixty-Two)
	(linked One-Hundred-and-Sixty-Two One-Hundred-and-Sixty-Four) 		(linked One-Hundred-and-Sixty-Four One-Hundred-and-Sixty-Two)
	(linked One-Hundred-and-Sixty-Three One-Hundred-and-Sixty-Five) 	(linked One-Hundred-and-Sixty-Five One-Hundred-and-Sixty-Three)
	(linked One-Hundred-and-Sixty-Three One-Hundred-and-Ninety-Eight) 	(linked One-Hundred-and-Ninety-Eight One-Hundred-and-Sixty-Three)
	(linked One-Hundred-and-Sixty-Four One-Hundred-and-Sixty-Five) 		(linked One-Hundred-and-Sixty-Five One-Hundred-and-Sixty-Four)
	(linked One-Hundred-and-Sixty-Five One-Hundred-and-Sixty-Six) 		(linked One-Hundred-and-Sixty-Six One-Hundred-and-Sixty-Five)
	(linked One-Hundred-and-Sixty-Five One-Hundred-and-Sixty-Nine) 		(linked One-Hundred-and-Sixty-Nine One-Hundred-and-Sixty-Five)
	(linked One-Hundred-and-Sixty-Six One-Hundred-and-Sixty-Seven) 		(linked One-Hundred-and-Sixty-Seven One-Hundred-and-Sixty-Six)
	(linked One-Hundred-and-Sixty-Seven One-Hundred-and-Sixty-Eight) 	(linked One-Hundred-and-Sixty-Eight One-Hundred-and-Sixty-Seven)
	(linked One-Hundred-and-Sixty-Eight One-Hundred-and-Sixty-Nine) 	(linked One-Hundred-and-Sixty-Nine One-Hundred-and-Sixty-Eight)
	(linked One-Hundred-and-Sixty-Eight One-Hundred-and-Seventy) 		(linked One-Hundred-and-Seventy One-Hundred-and-Sixty-Eight)
	(linked One-Hundred-and-Sixty-Nine One-Hundred-and-Seventy) 		(linked One-Hundred-and-Seventy One-Hundred-and-Sixty-Nine)
	(linked One-Hundred-and-Sixty-Nine One-Hundred-and-Eighty-Four) 	(linked One-Hundred-and-Eighty-Four One-Hundred-and-Sixty-Nine)
	(linked One-Hundred-and-Seventy One-Hundred-and-Eighty-Three) 		(linked One-Hundred-and-Eighty-Three One-Hundred-and-Seventy)
	(linked One-Hundred-and-Seventy-One One-Hundred-and-Seventy-Two) 	(linked One-Hundred-and-Seventy-Two One-Hundred-and-Seventy-One)
	(linked One-Hundred-and-Seventy-One One-Hundred-and-Seventy-Three) 	(linked One-Hundred-and-Seventy-Three One-Hundred-and-Seventy-One)
	(linked One-Hundred-and-Seventy-Two One-Hundred-and-Seventy-Four) 	(linked One-Hundred-and-Seventy-Four One-Hundred-and-Seventy-Two)
	(linked One-Hundred-and-Seventy-Three One-Hundred-and-Seventy-Four) (linked One-Hundred-and-Seventy-Four One-Hundred-and-Seventy-Three)
	(linked One-Hundred-and-Seventy-Three One-Hundred-and-Seventy-Five) (linked One-Hundred-and-Seventy-Five One-Hundred-and-Seventy-Three)
	(linked One-Hundred-and-Seventy-Three One-Hundred-and-Eighty-Two) 	(linked One-Hundred-and-Eighty-Two One-Hundred-and-Seventy-Three)
	(linked One-Hundred-and-Seventy-Four One-Hundred-and-Seventy-Five) 	(linked One-Hundred-and-Seventy-Five One-Hundred-and-Seventy-Four)
	(linked One-Hundred-and-Seventy-Five One-Hundred-and-Seventy-Six) 	(linked One-Hundred-and-Seventy-Six One-Hundred-and-Seventy-Five)
	(linked One-Hundred-and-Seventy-Six One-Hundred-and-Seventy-Seven) 	(linked One-Hundred-and-Seventy-Seven One-Hundred-and-Seventy-Six)
	(linked One-Hundred-and-Seventy-Six One-Hundred-and-Eighty) 		(linked One-Hundred-and-Eighty One-Hundred-and-Seventy-Six)
	(linked One-Hundred-and-Seventy-Seven One-Hundred-and-Seventy-Eight)(linked One-Hundred-and-Seventy-Eight One-Hundred-and-Seventy-Seven)
	(linked One-Hundred-and-Seventy-Seven One-Hundred-and-Seventy-Nine) (linked One-Hundred-and-Seventy-Nine One-Hundred-and-Seventy-Seven)

	(linked One-Hundred-and-Seventy-Nine One-Hundred-and-Eighty) 		(linked One-Hundred-and-Eighty One-Hundred-and-Seventy-Nine)	
	(linked One-Hundred-and-Seventy-Nine One-Hundred-and-Eighty-Seven) 	(linked One-Hundred-and-Eighty-Seven One-Hundred-and-Seventy-Nine)
	(linked One-Hundred-and-Eighty One-Hundred-and-Eighty-One) 			(linked One-Hundred-and-Eighty-One One-Hundred-and-Eighty)
	(linked One-Hundred-and-Eighty-One One-Hundred-and-Eighty-Two) 		(linked One-Hundred-and-Eighty-Two One-Hundred-and-Eighty-One)
	(linked One-Hundred-and-Eighty-One One-Hundred-and-Eighty-Six) 		(linked One-Hundred-and-Eighty-Six One-Hundred-and-Eighty-One)
	(linked One-Hundred-and-Eighty-Two One-Hundred-and-Eighty-Three) 	(linked One-Hundred-and-Eighty-Three One-Hundred-and-Eighty-Two)
	(linked One-Hundred-and-Eighty-Two One-Hundred-and-Eighty-Five) 	(linked One-Hundred-and-Eighty-Five One-Hundred-and-Eighty-Two)
	(linked One-Hundred-and-Eighty-Three One-Hundred-and-Eighty-Four) 	(linked One-Hundred-and-Eighty-Four One-Hundred-and-Eighty-Three)
	(linked One-Hundred-and-Eighty-Four One-Hundred-and-Eighty-Five) 	(linked One-Hundred-and-Eighty-Five One-Hundred-and-Eighty-Four)
	(linked One-Hundred-and-Eighty-Five One-Hundred-and-Eighty-Six) 	(linked One-Hundred-and-Eighty-Six One-Hundred-and-Eighty-Five)
	(linked One-Hundred-and-Eighty-Five One-Hundred-and-Ninety-Five) 	(linked One-Hundred-and-Ninety-Five One-Hundred-and-Eighty-Five)
	(linked One-Hundred-and-Eighty-Six One-Hundred-and-Eighty-Seven) 	(linked One-Hundred-and-Eighty-Seven One-Hundred-and-Eighty-Six)
	(linked One-Hundred-and-Eighty-Six One-Hundred-and-Ninety-Four) 	(linked One-Hundred-and-Ninety-Four One-Hundred-and-Eighty-Six)
	(linked One-Hundred-and-Eighty-Seven One-Hundred-and-Eighty-Eight) 	(linked One-Hundred-and-Eighty-Eight One-Hundred-and-Eighty-Seven)
	(linked One-Hundred-and-Eighty-Seven One-Hundred-and-Eighty-Nine) 	(linked One-Hundred-and-Eighty-Nine One-Hundred-and-Eighty-Seven)
	(linked One-Hundred-and-Eighty-Eight One-Hundred-and-Eighty-Nine) 	(linked One-Hundred-and-Eighty-Nine One-Hundred-and-Eighty-Eight)
	(linked One-Hundred-and-Eighty-Eight One-Hundred-and-Ninety-Four) 	(linked One-Hundred-and-Ninety-Four One-Hundred-and-Eighty-Eight)
	(linked One-Hundred-and-Eighty-Eight One-Hundred-and-Ninety-Three) 	(linked One-Hundred-and-Ninety-Three One-Hundred-and-Eighty-Eight)
	(linked One-Hundred-and-Eighty-Eight Two-Hundred-and-Twenty-Eight) 	(linked Two-Hundred-and-Twenty-Eight One-Hundred-and-Eighty-Eight)
	(linked One-Hundred-and-Eighty-Nine One-Hundred-and-Ninety) 		(linked One-Hundred-and-Ninety One-Hundred-and-Eighty-Nine)
		
	(linked One-Hundred-and-Ninety-One One-Hundred-and-Ninety-Two) 		(linked One-Hundred-and-Ninety-Two One-Hundred-and-Ninety-One)
	(linked One-Hundred-and-Ninety-One Two-Hundred-and-Twenty-Nine) 	(linked Two-Hundred-and-Twenty-Nine One-Hundred-and-Ninety-One)
	(linked One-Hundred-and-Ninety-Two One-Hundred-and-Ninety-Three) 	(linked One-Hundred-and-Ninety-Three One-Hundred-and-Ninety-Two)
	(linked One-Hundred-and-Ninety-Two Two-Hundred-and-Twenty-Eight) 	(linked Two-Hundred-and-Twenty-Eight One-Hundred-and-Ninety-Two)
	(linked One-Hundred-and-Ninety-Three One-Hundred-and-Ninety-Four) 	(linked One-Hundred-and-Ninety-Four One-Hundred-and-Ninety-Three)
	(linked One-Hundred-and-Ninety-Three One-Hundred-and-Ninety-Six) 	(linked One-Hundred-and-Ninety-Six One-Hundred-and-Ninety-Three)
	(linked One-Hundred-and-Ninety-Four One-Hundred-and-Ninety-Five) 	(linked One-Hundred-and-Ninety-Five One-Hundred-and-Ninety-Four)
	(linked One-Hundred-and-Ninety-Five One-Hundred-and-Ninety-Six) 	(linked One-Hundred-and-Ninety-Six One-Hundred-and-Ninety-Five)
	(linked One-Hundred-and-Ninety-Five One-Hundred-and-Ninety-Eight) 	(linked One-Hundred-and-Ninety-Eight One-Hundred-and-Ninety-Five)
	(linked One-Hundred-and-Ninety-Six One-Hundred-and-Ninety-Seven) 	(linked One-Hundred-and-Ninety-Seven One-Hundred-and-Ninety-Six)
	(linked One-Hundred-and-Ninety-Seven One-Hundred-and-Ninety-Eight)	(linked One-Hundred-and-Ninety-Eight One-Hundred-and-Ninety-Seven)
		
	(linked One-Hundred-and-Ninety-Nine Two-Hundred) 					(linked Two-Hundred One-Hundred-and-Ninety-Nine)
	(linked Two-Hundred Two-Hundred-and-One) 							(linked Two-Hundred-and-One Two-Hundred)	
	(linked Two-Hundred Two-Hundred-and-Eight) 							(linked Two-Hundred-and-Eight Two-Hundred)
	(linked Two-Hundred-and-One Two-Hundred-and-Two) 					(linked Two-Hundred-and-Two Two-Hundred-and-One)
	(linked Two-Hundred-and-One Two-Hundred-and-Nine) 					(linked Two-Hundred-and-Nine Two-Hundred-and-One)
	(linked Two-Hundred-and-Two Two-Hundred-and-Three) 					(linked Two-Hundred-and-Three Two-Hundred-and-Two)
	(linked Two-Hundred-and-Two Two-Hundred-and-Five) 					(linked Two-Hundred-and-Five Two-Hundred-and-Two)
	(linked Two-Hundred-and-Three Two-Hundred-and-Four) 				(linked Two-Hundred-and-Four Two-Hundred-and-Three)
	(linked Two-Hundred-and-Three Two-Hundred-and-Five) 				(linked Two-Hundred-and-Five Two-Hundred-and-Three)
	
	(linked Two-Hundred-and-Five Two-Hundred-and-Six) 					(linked Two-Hundred-and-Six Two-Hundred-and-Five)		
	(linked Two-Hundred-and-Five Two-Hundred-and-Nine) 					(linked Two-Hundred-and-Nine Two-Hundred-and-Five)
	(linked Two-Hundred-and-Six Two-Hundred-and-Seven) 					(linked Two-Hundred-and-Seven Two-Hundred-and-Six)
	(linked Two-Hundred-and-Seven Two-Hundred-and-Eight) 				(linked Two-Hundred-and-Eight Two-Hundred-and-Seven)
	(linked Two-Hundred-and-Seven Two-Hundred-and-Twelve) 				(linked Two-Hundred-and-Twelve Two-Hundred-and-Seven)
	(linked Two-Hundred-and-Eight Two-Hundred-and-Nine) 				(linked Two-Hundred-and-Nine Two-Hundred-and-Eight)
	(linked Two-Hundred-and-Eight Two-Hundred-and-Ten) 					(linked Two-Hundred-and-Ten Two-Hundred-and-Eight)
	
	(linked Two-Hundred-and-Ten Two-Hundred-and-Eleven) 				(linked Two-Hundred-and-Eleven Two-Hundred-and-Ten)
	(linked Two-Hundred-and-Eleven Two-Hundred-and-Twelve) 				(linked Two-Hundred-and-Twelve Two-Hundred-and-Eleven)		
	
	(linked Two-Hundred-and-Twenty-Two Two-Hundred-and-Twenty-Three) 	(linked Two-Hundred-and-Twenty-Three Two-Hundred-and-Twenty-Two)
	(linked Two-Hundred-and-Twenty-Three Two-Hundred-and-Twenty-Four) 	(linked Two-Hundred-and-Twenty-Four Two-Hundred-and-Twenty-Three)
	(linked Two-Hundred-and-Twenty-Three Two-Hundred-and-Thirty) 		(linked Two-Hundred-and-Thirty Two-Hundred-and-Twenty-Three)
	
	(= (space-available Ambulance-A) 10)
	(= (space-available Ambulance-B) 10)
	(= (space-available Ambulance-C) 10)
	(= (space-available Ambulance-D) 10)
	
	(= (beds-available St-Thomas-Hospital) 2)
	(= (beds-available Kings-College-Hospital) 2)

	(= (travel-time One Forty-Three) 1.7) 										(= (travel-time Forty-Three One) 1.7)
	(= (travel-time Two Two-Hundred-and-Sixteen) 0.8) 							(= (travel-time Two-Hundred-and-Sixteen Two) 0.8)
	(= (travel-time Three Two-Hundred-and-Fifteen) 0.4) 						(= (travel-time Two-Hundred-and-Fifteen Three) 0.4)
	(= (travel-time Four Two-Hundred-and-Fourteen) 0.5)							(= (travel-time Two-Hundred-and-Fourteen Four) 0.5)
	(= (travel-time Forty-Five Two-Hundred-and-Fourteen) 0.9) 					(= (travel-time Two-Hundred-and-Fourteen Forty-Five) 0.9)
	(= (travel-time Forty-Five Forty-Eight) 1.2)								(= (travel-time Forty-Eight Forty-Five) 1.2)	
	(= (travel-time Forty-Five Forty-Six) 0.7)									(= (travel-time Forty-Six Forty-Five) 0.7)
	(= (travel-time Forty-Four Forty-Six) 0.5)									(= (travel-time Forty-Six Forty-Four) 0.5)
	(= (travel-time Five Forty-Eight) 1.3)										(= (travel-time Forty-Eight Five) 1.3)
	(= (travel-time Six Fifty-Three) 0.8)										(= (travel-time Fifty-Three Six) 0.8)
	(= (travel-time Seven Fifty-Four) 0.4)										(= (travel-time Fifty-Four Seven) 0.4)
	(= (travel-time Fifty-Three Fifty-Four) 1.1)								(= (travel-time Fifty-Four Fifty-Three) 1.1)
	(= (travel-time Eight Fifty-Four) 0.2)										(= (travel-time Fifty-Four Eight) 0.2)
	(= (travel-time Fifty-Three Fifty-Two) 1.1)									(= (travel-time Fifty-Two Fifty-Three) 1.1)
	(= (travel-time Fifty-Two Fifty-Five) 1.1)									(= (travel-time Fifty-Five Fifty-Two) 1.1)
	(= (travel-time Fifty-Four Fifty-Five) 0.8)									(= (travel-time Fifty-Five Fifty-Four) 0.8)
	(= (travel-time Fifty-Two Fifty-One) 0.1)									(= (travel-time Fifty-One Fifty-Two) 0.1)
	(= (travel-time Fifty-One Two-Hundred-and-Seventeen) 0.5)					(= (travel-time Two-Hundred-and-Seventeen Fifty-One) 0.5)
	(= (travel-time Two-Hundred-and-Sixteen Forty-Three) 0.8)					(= (travel-time Forty-Three Two-Hundred-and-Sixteen) 0.8)
	(= (travel-time Two-Hundred-and-Fifteen Two-Hundred-and-Fourteen) 0.4)		(= (travel-time Two-Hundred-and-Fourteen Two-Hundred-and-Fifteen) 0.4)
	(= (travel-time Two-Hundred-and-Fifteen Two-Hundred-and-Sixteen) 0.3)		(= (travel-time Two-Hundred-and-Sixteen Two-Hundred-and-Fifteen) 0.3)
	(= (travel-time Two-Hundred-and-Fifteen Forty-Four) 1)						(= (travel-time Forty-Four Two-Hundred-and-Fifteen) 1)
	(= (travel-time Forty-Eight Forty-Nine) 0.3)								(= (travel-time Forty-Nine Forty-Eight) 0.3)
	(= (travel-time Forty-Nine Forty-Seven) 0.6)								(= (travel-time Forty-Seven Forty-Nine) 0.6)
	(= (travel-time Forty-Seven Forty-Six) 0.6)									(= (travel-time Forty-Six Forty-Seven) 0.6)
	(= (travel-time Fifty Sixty-Eight) 0.7)										(= (travel-time Sixty-Eight Fifty) 0.7)
	(= (travel-time Forty-Nine Fifty) 0.4)										(= (travel-time Fifty Forty-Nine) 0.4)
	(= (travel-time Forty-Three Seventy-Nine) 1)								(= (travel-time Seventy-Nine Forty-Three) 1)
	(= (travel-time Forty-Four Seventy-Six) 1.3)								(= (travel-time Seventy-Six Forty-Four) 1.3)
	(= (travel-time Eighty Forty-Two) 0.6)										(= (travel-time Forty-Two Eighty) 0.6)
	(= (travel-time Forty-Two Eighty-Two) 2)									(= (travel-time Eighty-Two Forty-Two) 2)
	(= (travel-time Fifty Sixty-Six) 0.6)										(= (travel-time Sixty-Six Fifty) 0.6)
	(= (travel-time Fifty-Seven Two-Hundred-and-Seventeen) 1)					(= (travel-time Two-Hundred-and-Seventeen Fifty-Seven) 1)
	(= (travel-time Two-Hundred-and-Seventeen Sixty-Two) 0.2)					(= (travel-time Sixty-Two Two-Hundred-and-Seventeen) 0.2)
	(= (travel-time Sixty-Two Sixty-Four) 0.5)									(= (travel-time Sixty-Four Sixty-Two) 0.5)
	(= (travel-time Fifty-Nine Sixty-Two) 0.8)									(= (travel-time Sixty-Two Fifty-Nine) 0.8)
	(= (travel-time Fifty-One Forty-Nine) 0.8)									(= (travel-time Forty-Nine Fifty-One) 0.8)
	(= (travel-time Sixty-Four Sixty-Five) 0.2)									(= (travel-time Sixty-Five Sixty-Four) 0.2)
	(= (travel-time Forty-Four Seventy-Three) 1.2)								(= (travel-time Seventy-Three Forty-Four) 1.2)
	(= (travel-time Forty-Four Seventy) 1.9)									(= (travel-time Seventy Forty-Four) 1.9)
	(= (travel-time Seventy Seventy-One) 0.5)									(= (travel-time Seventy-One Seventy) 0.5)
	(= (travel-time Seventy Sixty-Nine) 0.3)									(= (travel-time Sixty-Nine Seventy) 0.3)
	(= (travel-time Forty-Seven Sixty-Nine) 0.5)								(= (travel-time Sixty-Nine Forty-Seven) 0.5)
	(= (travel-time Seventy-One Sixty-Nine) 0.7)								(= (travel-time Sixty-Nine Seventy-One) 0.7)
	(= (travel-time Sixty-Eight Sixty-Seven) 1.2)								(= (travel-time Sixty-Seven Sixty-Eight) 1.2)
	(= (travel-time Sixty-Seven Sixty-Six) 0.6)									(= (travel-time Sixty-Six Sixty-Seven) 0.6)
	(= (travel-time Eighty Seventy-Eight) 0.8)									(= (travel-time Seventy-Eight Eighty) 0.8)
	(= (travel-time Seventy-Nine Seventy-Eight) 0.5)							(= (travel-time Seventy-Eight Seventy-Nine) 0.5)
	(= (travel-time Eighty-Two Seventy-Seven) 0.8)								(= (travel-time Seventy-Seven Eighty-Two) 0.8)
	(= (travel-time Eighty-Four Eighty-Three) 0.4)								(= (travel-time Eighty-Three Eighty-Four) 0.4)
	(= (travel-time Eighty-Four Seventy-Seven) 0.3)								(= (travel-time Seventy-Seven Eighty-Four) 0.3)
	(= (travel-time Seventy-Six Seventy-Seven) 0.5)								(= (travel-time Seventy-Seven Seventy-Six) 0.5)
	(= (travel-time Seventy-Seven Seventy-Eight) 0.3)							(= (travel-time Seventy-Eight Seventy-Seven) 0.3)
	(= (travel-time Seventy-Nine Seventy-Six) 0.3)								(= (travel-time Seventy-Six Seventy-Nine) 0.3)
	(= (travel-time Eighty-Two Two-Hundred-and-Thirteen) 0.5)					(= (travel-time Two-Hundred-and-Thirteen Eighty-Two) 0.5)
	(= (travel-time Eighty-Four Eighty-Five) 0.9)								(= (travel-time Eighty-Five Eighty-Four) 0.9)
	(= (travel-time Eighty-Five Eighty-Six) 0.6)								(= (travel-time Eighty-Six Eighty-Five) 0.6)
	(= (travel-time Eighty-Six Two-Hundred-and-Thirteen) 0.9)					(= (travel-time Two-Hundred-and-Thirteen Eighty-Six) 0.9)
	(= (travel-time Fifty-Five Fifty-Six) 0.3)									(= (travel-time Fifty-Six Fifty-Five) 0.3)
	(= (travel-time Fifty-Six Fifty-Seven) 0.3)									(= (travel-time Fifty-Seven Fifty-Six) 0.3)
	(= (travel-time Fifty-Six Two-Hundred-and-Eighteen) 0.7)					(= (travel-time Two-Hundred-and-Eighteen Fifty-Six) 0.7)
	(= (travel-time Two-Hundred-and-Eighteen Nine) 0.1)							(= (travel-time Nine Two-Hundred-and-Eighteen) 0.1)
	(= (travel-time Two-Hundred-and-Eighteen Ten) 0.1)							(= (travel-time Ten Two-Hundred-and-Eighteen) 0.1)
	(= (travel-time Two-Hundred-and-Eighteen Two-Hundred-and-Nineteen) 0.1)		(= (travel-time Two-Hundred-and-Nineteen Two-Hundred-and-Eighteen) 0.1)
	(= (travel-time Two-Hundred-and-Nineteen Fifty-Seven) 0.7)					(= (travel-time Fifty-Seven Two-Hundred-and-Nineteen) 0.7)
	(= (travel-time Seventy-Three Seventy-Four) 0.4)							(= (travel-time Seventy-Four Seventy-Three) 0.4)
	(= (travel-time Seventy-Three Seventy-Two) 0.3)								(= (travel-time Seventy-Two Seventy-Three) 0.3)
	(= (travel-time Seventy-Two Seventy-Four) 0.4)								(= (travel-time Seventy-Four Seventy-Two) 0.4)
	(= (travel-time Seventy-Four Seventy-Six) 0.3)								(= (travel-time Seventy-Six Seventy-Four) 0.3)
	(= (travel-time Seventy-Four Eighty-Four) 0.4)								(= (travel-time Eighty-Four Seventy-Four) 0.4)
	(= (travel-time Seventy-Four Seventy-Five) 0.3)								(= (travel-time Seventy-Five Seventy-Four) 0.3)
	(= (travel-time Sixty-Five Eighty-Eight) 0.4)								(= (travel-time Eighty-Eight Sixty-Five) 0.4)
	(= (travel-time Sixty-Seven Eighty-Eight) 0.7)								(= (travel-time Sixty-Seven Eighty-Eight) 0.7)
	(= (travel-time Sixty-Seven Eighty-Five) 0.3)								(= (travel-time Eighty-Five Sixty-Seven) 0.3)
	(= (travel-time Eighty-Nine Eighty-Eight) 0.4)								(= (travel-time Eighty-Eight Eighty-Nine) 0.4)
	(= (travel-time Sixty-Four Sixty-Three) 0.3)								(= (travel-time Sixty-Three Sixty-Four) 0.3)
	(= (travel-time Sixty-One Sixty-Three) 0.9)									(= (travel-time Sixty-Three Sixty-One) 0.9)
	(= (travel-time Fifty-Nine Sixty-One) 0.8)									(= (travel-time Sixty-One Fifty-Nine) 0.8)
	(= (travel-time Two-Hundred-and-Thirteen One-Hundred-and-Forty-One) 0.8)	(= (travel-time One-Hundred-and-Forty-One Two-Hundred-and-Fourteen) 0.8)
	(= (travel-time One-Hundred-and-Forty-Two One-Hundred-and-Forty-One) 0.8)	(= (travel-time One-Hundred-and-Forty-One One-Hundred-and-Forty-Two) 0.8)
	(= (travel-time Eighty-Six Eighty-Seven) 0.5)								(= (travel-time Eighty-Seven Eighty-Six) 0.5)
	(= (travel-time Eighty-Nine Eighty-Seven) 0.8)								(= (travel-time Eighty-Seven Eighty-Nine) 0.8)
	(= (travel-time Eighty-Seven One-Hundred-and-Forty) 0.4)					(= (travel-time One-Hundred-and-Forty Eighty-Seven) 0.4)
	(= (travel-time One-Hundred-and-Forty One-Hundred-and-Forty-One) 1.1)		(= (travel-time One-Hundred-and-Forty-One One-Hundred-and-Forty) 1.1)
	(= (travel-time Ninety Eighty-Nine) 0.4)									(= (travel-time Eighty-Nine Ninety) 0.4)
	(= (travel-time Sixty-Three Ninety-Two) 0.9)								(= (travel-time Ninety-Two Sixty-Three) 0.9)
	(= (travel-time Fifty-Nine Fifty-Eight) 0.1)								(= (travel-time Fifty-Eight Fifty-Nine) 0.1)
	(= (travel-time Fifty-Seven Fifty-Eight) 0.3)								(= (travel-time Fifty-Eight Fifty-Seven) 0.3)
	(= (travel-time Fifty-Eight Sixty) 0.5)										(= (travel-time Sixty Fifty-Eight) 0.5)
	(= (travel-time Two-Hundred-and-Nineteen Two-Hundred-and-Twenty) 0.1)		(= (travel-time Two-Hundred-and-Twenty Two-Hundred-and-Nineteen) 0.1)
	(= (travel-time Two-Hundred-and-Twenty Sixty) 0.5)							(= (travel-time Sixty Two-Hundred-and-Twenty) 0.5)
	(= (travel-time Two-Hundred-and-Twenty Eleven) 0.2)							(= (travel-time Eleven Two-Hundred-and-Twenty) 0.2)
	(= (travel-time Two-Hundred-and-Twenty-One Sixty) 0.2)						(= (travel-time Sixty Two-Hundred-and-Twenty-One) 0.2)
	(= (travel-time Ninety-Nine Sixty) 0.4)										(= (travel-time Sixty Ninety-Nine) 0.4)
	(= (travel-time Sixty Sixty-One) 0.4)										(= (travel-time Sixty-One Sixty) 0.4)
	(= (travel-time Twelve Two-Hundred-and-Twenty-One) 0.6)						(= (travel-time Two-Hundred-and-Twenty-One Twelve) 0.6)
	(= (travel-time Thirteen Two-Hundred-and-Twenty-One) 0.6)					(= (travel-time Two-Hundred-and-Twenty-One Thirteen) 0.6)
	(= (travel-time One-Hundred Two-Hundred-and-Twenty-One) 0.7)				(= (travel-time Two-Hundred-and-Twenty-One One-Hundred) 0.7)
	(= (travel-time Ninety-Nine One-Hundred) 0.8)								(= (travel-time One-Hundred Ninety-Nine) 0.8)
	(= (travel-time One-Hundred One-Hundred-and-One) 0.2)						(= (travel-time One-Hundred-and-One One-Hundred) 0.2)
	(= (travel-time One-Hundred-and-One One-Hundred-and-Two) 0.7)				(= (travel-time One-Hundred-and-Two One-Hundred-and-One) 0.7)
	(= (travel-time Two-Hundred-and-Thirty One-Hundred-and-One) 0.8)			(= (travel-time One-Hundred-and-One Two-Hundred-and-Thirty) 0.8)
	(= (travel-time One-Hundred-and-Two One-Hundred-and-Three) 0.3)				(= (travel-time One-Hundred-and-Three One-Hundred-and-Two) 0.3)
	(= (travel-time One-Hundred-and-Two Two-Hundred-and-Twenty-Two) 0.4)		(= (travel-time Two-Hundred-and-Twenty-Two One-Hundred-and-Two) 0.4)
	(= (travel-time Two-Hundred-and-Twenty-Two One-Hundred-and-Three) 0.3)		(= (travel-time One-Hundred-and-Three Two-Hundred-and-Twenty-Two) 0.3)
	(= (travel-time Two-Hundred-and-Twenty-Two Two-Hundred-and-Twenty-Three) 0.2) (= (travel-time Two-Hundred-and-Twenty-Three Two-Hundred-and-Twenty-Two) 0.2)
	(= (travel-time Two-Hundred-and-Thirty Two-Hundred-and-Twenty-Three) 0.3)	(= (travel-time Two-Hundred-and-Twenty-Three Two-Hundred-and-Thirty) 0.3)
	(= (travel-time Ninety-Nine Ninety-Eight) 0.1)								(= (travel-time Ninety-Eight Ninety-Nine) 0.1)
	(= (travel-time Ninety-Eight Two-Hundred-and-Thirty) 0.1)					(= (travel-time Two-Hundred-and-Thirty Ninety-Eight) 0.1)
	(= (travel-time Sixty-One Two-Hundred-and-Thirty-One) 0.1)					(= (travel-time Two-Hundred-and-Thirty-One Sixty-One) 0.1)
	(= (travel-time Two-Hundred-and-Thirty-One Ninety-Nine) 0.2)				(= (travel-time Ninety-Nine Two-Hundred-and-Thirty-One) 0.2)
	(= (travel-time Two-Hundred-and-Thirty-One Ninety-Seven) 0.1)				(= (travel-time Ninety-Seven Two-Hundred-and-Thirty-One) 0.1)
	(= (travel-time Ninety-Seven Ninety-Eight) 0.1)								(= (travel-time Ninety-Eight Ninety-Seven) 0.1)
	(= (travel-time Ninety-Seven Ninety-Six) 0.2)								(= (travel-time Ninety-Six Ninety-Seven) 0.2)
	(= (travel-time Two-Hundred-and-Twenty-Three Two-Hundred-and-Twenty-Four) 0.1) 	(= (travel-time Two-Hundred-and-Twenty-Four Two-Hundred-and-Twenty-Three) 0.1)
	(= (travel-time Ninety-Six Two-Hundred-and-Twenty-Four) 0.3)					(= (travel-time Two-Hundred-and-Twenty-Four Ninety-Six) 0.3)
	(= (travel-time Ninety-Six Ninety-Five) 0.6)									(= (travel-time Ninety-Five Ninety-Six) 0.6)
	(= (travel-time Ninety-Five Ninety-Three) 0.2)									(= (travel-time Ninety-Three Ninety-Five) 0.2)
	(= (travel-time Ninety-Two Ninety-Three) 0.3)									(= (travel-time Ninety-Three Ninety-Two) 0.3)
	(= (travel-time Ninety-Five Ninety-Four) 0.3)									(= (travel-time Ninety-Four Ninety-Five) 0.3)
	(= (travel-time Ninety-Three Ninety-Four) 0.2)								(= (travel-time Ninety-Four Ninety-Three) 0.2)
	(= (travel-time Ninety-Two Ninety-One) 0.1)									(= (travel-time Ninety-One Ninety-Two) 0.1)
	(= (travel-time Ninety-One Ninety) 0.2)										(= (travel-time Ninety Ninety-One) 0.2)
	(= (travel-time Ninety One-Hundred-and-Thirty-Nine) 0.5)					(= (travel-time One-Hundred-and-Thirty-Nine Ninety) 0.5)
	(= (travel-time One-Hundred-and-Thirty-Nine One-Hundred-and-Forty) 0.5)		(= (travel-time One-Hundred-and-Forty One-Hundred-and-Thirty-Nine) 0.5)
	(= (travel-time Ninety One-Hundred-and-Thirty-Seven) 0.6)					(= (travel-time One-Hundred-and-Thirty-Seven Ninety) 0.6)
	(= (travel-time One-Hundred-and-Thirty-Nine One-Hundred-and-Thirty-Eight) 0.3)	(= (travel-time One-Hundred-and-Thirty-Eight One-Hundred-and-Thirty-Nine) 0.3)
	(= (travel-time One-Hundred-and-Thirty-Eight One-Hundred-and-Thirty-Seven) 0.2)	(= (travel-time One-Hundred-and-Thirty-Seven One-Hundred-and-Thirty-Eight) 0.2)
	(= (travel-time Ninety-One One-Hundred-and-Thirty-Six) 0.4)						(= (travel-time One-Hundred-and-Thirty-Six Ninety-One) 0.4)
	(= (travel-time One-Hundred-and-Thirty-Six One-Hundred-and-Twenty-Seven) 0.2)	(= (travel-time One-Hundred-and-Twenty-Seven One-Hundred-and-Thirty-Six) 0.2)
	(= (travel-time One-Hundred-and-Thirty-Six One-Hundred-and-Thirty-Seven) 0.4)	(= (travel-time One-Hundred-and-Thirty-Seven One-Hundred-and-Thirty-Six) 0.4)
	(= (travel-time Ninety-Four One-Hundred-and-Twenty-Seven) 0.2)					(= (travel-time One-Hundred-and-Twenty-Seven Ninety-Four) 0.2)
	(= (travel-time Two-Hundred-and-Twenty-Four One-Hundred-and-Seven) 0.4)			(= (travel-time One-Hundred-and-Seven Two-Hundred-and-Twenty-Four) 0.4)
	(= (travel-time Two-Hundred-and-Twenty-Three One-Hundred-and-Six) 0.3)			(= (travel-time One-Hundred-and-Six Two-Hundred-and-Twenty-Three) 0.3)
	(= (travel-time One-Hundred-and-Seven One-Hundred-and-Six) 0.3)					(= (travel-time One-Hundred-and-Six One-Hundred-and-Three) 0.3)
	(= (travel-time One-Hundred-and-Six One-Hundred-and-Four) 0.1)					(= (travel-time One-Hundred-and-Four One-Hundred-and-Six) 0.1)
	(= (travel-time One-Hundred-and-Three One-Hundred-and-Four) 0.1)				(= (travel-time One-Hundred-and-Four One-Hundred-and-Three) 0.1)
	(= (travel-time One-Hundred-and-Four One-Hundred-and-Five) 0.1)					(= (travel-time One-Hundred-and-Five One-Hundred-and-Four) 0.1)
	(= (travel-time One-Hundred-and-Five One-Hundred-and-Seven) 0.2)				(= (travel-time One-Hundred-and-Seven One-Hundred-and-Five) 0.2)
	(= (travel-time One-Hundred-and-Five One-Hundred-and-Eight) 0.2)				(= (travel-time One-Hundred-and-Eight One-Hundred-and-Five) 0.2)
	(= (travel-time One-Hundred-and-Eight One-Hundred-and-Seven) 0.4)				(= (travel-time One-Hundred-and-Seven One-Hundred-and-Five) 0.4)
	(= (travel-time One-Hundred-and-Five One-Hundred-and-Twenty-Five) 2)			(= (travel-time One-Hundred-and-Twenty-Five One-Hundred-and-Five) 2)
	(= (travel-time One-Hundred-and-Eight One-Hundred-and-Twenty-Seven) 0.3)		(= (travel-time One-Hundred-and-Twenty-Seven One-Hundred-and-Five) 0.3)
	(= (travel-time One-Hundred-and-Eight One-Hundred-and-Twenty-Nine) 2.7)			(= (travel-time One-Hundred-and-Twenty-Nine One-Hundred-and-Eight) 2.7)
	(= (travel-time One-Hundred-and-Twenty-Eight One-Hundred-and-Twenty-Nine) 0.5)	(= (travel-time One-Hundred-and-Twenty-Nine One-Hundred-and-Twenty-Eight) 0.5)
	(= (travel-time One-Hundred-and-Twenty-Seven One-Hundred-and-Twenty-Eight) 0.2)	(= (travel-time One-Hundred-and-Twenty-Eight One-Hundred-and-Twenty-Seven) 0.2)
	(= (travel-time One-Hundred-and-Twenty-Eight One-Hundred-and-Thirty-Five) 0.1)	(= (travel-time One-Hundred-and-Twenty-Five One-Hundred-and-Twenty-Eight) 0.1)
	(= (travel-time One-Hundred-and-Thirty-Six One-Hundred-and-Thirty-Five) 0.3)	(= (travel-time One-Hundred-and-Thirty-Five One-Hundred-and-Thirty-Six) 0.3)
	(= (travel-time One-Hundred-and-Twenty-Nine One-Hundred-and-Thirty) 0.9)		(= (travel-time One-Hundred-and-Thirty One-Hundred-and-Twenty-Nine) 0.9)
	(= (travel-time One-Hundred-and-Thirty One-Hundred-and-Thirty-One) 1)			(= (travel-time One-Hundred-and-Thirty-One One-Hundred-and-Thirty) 1)
	(= (travel-time One-Hundred-and-Twenty-Five One-Hundred-and-Twenty-Six) 3)		(= (travel-time One-Hundred-and-Twenty-Six One-Hundred-and-Twenty-Five) 3)
	(= (travel-time One-Hundred-and-Twenty-Five One-Hundred-and-Twenty-Four) 0.8)	(= (travel-time One-Hundred-and-Twenty-Four One-Hundred-and-Twenty-Five) 0.8)
	(= (travel-time One-Hundred-and-Nine One-Hundred-and-Four) 0.6)					(= (travel-time One-Hundred-and-Four One-Hundred-and-Nine) 0.6)
	(= (travel-time One-Hundred-and-Two One-Hundred-and-Ten) 0.2)					(= (travel-time One-Hundred-and-Ten One-Hundred-and-Two) 0.2)
	(= (travel-time One-Hundred-and-Ten One-Hundred-and-Nine) 0.6)					(= (travel-time One-Hundred-and-Nine One-Hundred-and-Ten) 0.6)
	(= (travel-time One-Hundred-and-Thirty-One One-Hundred-and-Twenty-Six) 0.7)		(= (travel-time One-Hundred-and-Twenty-Six One-Hundred-and-Thirty-One) 0.7)
	(= (travel-time One-Hundred-and-Twenty-Six One-Hundred-and-Twenty-Eight) 0.8)	(= (travel-time One-Hundred-and-Twenty-Eight One-Hundred-and-Twenty-Six) 0.8)
	(= (travel-time One-Hundred-and-Twenty-Six One-Hundred-and-Sixty-Seven) 0.9)	(= (travel-time One-Hundred-and-Sixty-Seven One-Hundred-and-Twenty-Six) 0.9)
	(= (travel-time One-Hundred-and-Thirty-Five One-Hundred-and-Thirty-Four) 0.3)	(= (travel-time One-Hundred-and-Thirty-Four One-Hundred-and-Thirty-Five) 0.3)
	(= (travel-time One-Hundred-and-Twenty-Nine One-Hundred-and-Thirty-Four) 0.1)	(= (travel-time One-Hundred-and-Thirty-Four One-Hundred-and-Twenty-Nine) 0.1)
	(= (travel-time One-Hundred-and-Thirty-Four One-Hundred-and-Thirty-Three) 0.6)	(= (travel-time One-Hundred-and-Thirty-Three One-Hundred-and-Thirty-Four) 0.6)
	(= (travel-time One-Hundred-and-Thirty One-Hundred-and-Thirty-Three) 0.4)		(= (travel-time One-Hundred-and-Thirty-Three One-Hundred-and-Thirty) 0.4)
	(= (travel-time One-Hundred-and-Thirty-Four One-Hundred-and-Fifty) 0.5)			(= (travel-time One-Hundred-and-Fifty One-Hundred-and-Thirty-Four) 0.5)
	(= (travel-time One-Hundred-and-Fifty One-Hundred-and-Forty-Eight) 0.3)			(= (travel-time One-Hundred-and-Forty-Eight One-Hundred-and-Fifty) 0.3)
	(= (travel-time One-Hundred-and-Forty-Eight One-Hundred-and-Forty-Nine) 0.3)	(= (travel-time One-Hundred-and-Forty-Nine One-Hundred-and-Eight) 0.3)
	(= (travel-time One-Hundred-and-Forty-Nine One-Hundred-and-Thirty-Three) 0.5)	(= (travel-time One-Hundred-and-Thirty-Three One-Hundred-and-Forty-Nine) 0.5)
	(= (travel-time One-Hundred-and-Thirty-Three One-Hundred-and-Thirty-Two) 0.5)	(= (travel-time One-Hundred-and-Thirty-Two One-Hundred-and-Thirty-Three) 0.5)
	(= (travel-time One-Hundred-and-Thirty-One One-Hundred-and-Thirty-Two) 1.2)		(= (travel-time One-Hundred-and-Thirty-Two One-Hundred-and-Thirty-One) 1.2)
	(= (travel-time One-Hundred-and-Thirty-Five One-Hundred-and-Fifty-One) 0.6)		(= (travel-time One-Hundred-and-Fifty-One One-Hundred-and-Thirty-Five) 0.6)
	(= (travel-time Two-Hundred-and-Twenty-Six One-Hundred-and-Fifty-One) 2)		(= (travel-time One-Hundred-and-Fifty-One Two-Hundred-and-Twenty-Six) 2)
	(= (travel-time One-Hundred-and-Thirty-Eight One-Hundred-and-Fifty-One) 0.6)	(= (travel-time One-Hundred-and-Fifty-One One-Hundred-and-Thirty-Eight) 0.6)
	(= (travel-time One-Hundred-and-Fifty One-Hundred-and-Fifty-One) 0.3)			(= (travel-time One-Hundred-and-Fifty-One One-Hundred-and-Fifty) 0.3)
	(= (travel-time One-Hundred-and-Fifty-One Two-Hundred-and-Twenty-Six) 1.1)		(= (travel-time Two-Hundred-and-Twenty-Six One-Hundred-and-Fifty-One) 1.1)
	(= (travel-time One-Hundred-and-Thirty-Three Two-Hundred-and-Twenty-Seven) 0.3)	(= (travel-time Two-Hundred-and-Twenty-Seven One-Hundred-and-Thirty-Three) 0.3)
	(= (travel-time One-Hundred-and-Thirty-Two Two-Hundred-and-Twenty-Seven) 3)		(= (travel-time Two-Hundred-and-Twenty-Seven Two-Hundred-and-Twenty-Two) 3)
	(= (travel-time One-Hundred-and-Forty-Nine Thirty-Eight) 3.4)					(= (travel-time Thirty-Eight One-Hundred-and-Forty-Nine) 3.4)
	(= (travel-time Two-Hundred-and-Twenty-Seven Thirty-Eight) 3.4)					(= (travel-time Thirty-Eight Two-Hundred-and-Twenty-Seven) 3.4)
	(= (travel-time One-Hundred-and-Thirty-Two One-Hundred-and-Sixty-Two) 1)		(= (travel-time One-Hundred-and-Sixty-Two One-Hundred-and-Thirty-Two) 1)
	(= (travel-time One-Hundred-and-Sixty-Two One-Hundred-and-Sixty-Three) 1.3)		(= (travel-time One-Hundred-and-Sixty-Three One-Hundred-and-Sixty-Two) 1.3)
	(= (travel-time One-Hundred-and-Sixty-Three One-Hundred-and-Ninety-Eight) 3)	(= (travel-time One-Hundred-and-Ninety-Eight One-Hundred-and-Sixty-Three) 3)
	(= (travel-time One-Hundred-and-Ninety-Eight One-Hundred-and-Ninety-Seven) 0.9)	(= (travel-time One-Hundred-and-Ninety-Seven One-Hundred-and-Ninety-Eight) 0.9)
	(= (travel-time One-Hundred-and-Ninety-Seven One-Hundred-and-Ninety-Six) 0.1)	(= (travel-time One-Hundred-and-Ninety-Six One-Hundred-and-Ninety-Seven) 0.1)
	(= (travel-time One-Hundred-and-Ninety-Six One-Hundred-and-Ninety-Three) 0.6)	(= (travel-time One-Hundred-and-Ninety-Three One-Hundred-and-Ninety-Six) 0.6)
	(= (travel-time Two-Hundred-and-Twenty-Seven One-Hundred-and-Fifty-Three) 0.2)	(= (travel-time One-Hundred-and-Fifty-Three Two-Hundred-and-Twenty-Seven) 0.2)
	(= (travel-time One-Hundred-and-Fifty-Three One-Hundred-and-Fifty-Four) 0.5)	(= (travel-time One-Hundred-and-Fifty-Four One-Hundred-and-Fifty-Three) 0.5)
	(= (travel-time One-Hundred-and-Fifty-Four One-Hundred-and-Sixty-Two) 0.3)		(= (travel-time One-Hundred-and-Sixty-Two One-Hundred-and-Fifty-Four) 0.3)
	(= (travel-time One-Hundred-and-Sixty-Two One-Hundred-and-Sixty-Four) 1.2)		(= (travel-time One-Hundred-and-Sixty-Four One-Hundred-and-Sixty-Two) 1.2)
	(= (travel-time One-Hundred-and-Forty-One Two-Hundred-and-Twenty-Six) 0.5)		(= (travel-time Two-Hundred-and-Twenty-Six One-Hundred-and-Forty-One) 0.5)
	(= (travel-time One-Hundred-and-Forty-Two Two-Hundred-and-Twenty-Six) 1.5)		(= (travel-time Two-Hundred-and-Twenty-Six One-Hundred-and-Forty-Two) 1.5)
	(= (travel-time One-Hundred-and-Forty-Two Forty-One) 0.6)						(= (travel-time Forty-One One-Hundred-and-Forty-Two) 0.6)
	(= (travel-time One-Hundred-and-Forty-Two One-Hundred-and-Forty-Three) 0.4)		(= (travel-time One-Hundred-and-Forty-Three One-Hundred-and-Forty-Two) 0.4)
	(= (travel-time Forty One-Hundred-and-Forty-Three) 0.5)							(= (travel-time One-Hundred-and-Forty-Three Forty) 0.5)
	(= (travel-time One-Hundred-and-Forty-Three One-Hundred-and-Forty-Four) 0.6)	(= (travel-time One-Hundred-and-Forty-Four One-Hundred-and-Forty-Three) 0.6)
	(= (travel-time Two-Hundred-and-Twenty-Six One-Hundred-and-Forty-Four) 0.3)		(= (travel-time One-Hundred-and-Forty-Four Two-Hundred-and-Twenty-Six) 0.3)
	(= (travel-time One-Hundred-and-Forty-Four One-Hundred-and-Forty-Five) 0.4)		(= (travel-time One-Hundred-and-Forty-Five One-Hundred-and-Forty-Four) 0.4)
	(= (travel-time One-Hundred-and-Fifty-Three One-Hundred-and-Fifty-Five) 1.9)	(= (travel-time One-Hundred-and-Fifty-Five One-Hundred-and-Fifty-Three) 1.9)
	(= (travel-time One-Hundred-and-Fifty-Four One-Hundred-and-Fifty-Five) 1.9)		(= (travel-time One-Hundred-and-Fifty-Five One-Hundred-and-Fifty-Four) 1.9)
	(= (travel-time One-Hundred-and-Fifty-Five One-Hundred-and-Fifty-Six) 1.4)		(= (travel-time One-Hundred-and-Fifty-Six One-Hundred-and-Fifty-Five) 1.4)
	(= (travel-time One-Hundred-and-Fifty-Six Thirty-Seven) 0.8)					(= (travel-time Thirty-Seven One-Hundred-and-Fifty-Six) 0.8)
	(= (travel-time One-Hundred-and-Fifty-Six One-Hundred-and-Fifty-Seven) 0.9)		(= (travel-time One-Hundred-and-Fifty-Seven One-Hundred-and-Fifty-Six) 0.9)
	(= (travel-time One-Hundred-and-Fifty-Seven Thirty-Six) 0.6)					(= (travel-time Thirty-Six One-Hundred-and-Fifty-Seven) 0.6)
	(= (travel-time One-Hundred-and-Fifty-Seven Thirty-Five) 0.7)					(= (travel-time Thirty-Five One-Hundred-and-Fifty-Seven) 0.7)
	(= (travel-time One-Hundred-and-Fifty-Seven One-Hundred-and-Fifty-Eight) 0.4)	(= (travel-time One-Hundred-and-Fifty-Eight One-Hundred-and-Fifty-Seven) 0.4)
	(= (travel-time One-Hundred-and-Fifty-Eight One-Hundred-and-Sixty-One) 0.5)		(= (travel-time One-Hundred-and-Sixty-One One-Hundred-and-Fifty-Eight) 0.5)
	(= (travel-time One-Hundred-and-Sixty-One Thirty-Four) 0.6)						(= (travel-time Thirty-Four One-Hundred-and-Sixty-One) 0.6)
	(= (travel-time One-Hundred-and-Sixty One-Hundred-and-Sixty-One) 1.6)			(= (travel-time One-Hundred-and-Sixty-One One-Hundred-and-Sixty) 1.6)
	(= (travel-time One-Hundred-and-Fifty-Eight One-Hundred-and-Sixty) 1)			(= (travel-time One-Hundred-and-Sixty One-Hundred-and-Fifty-Eight) 1)
	(= (travel-time One-Hundred-and-Fifty-Eight One-Hundred-and-Fifty-Nine) 0.5)	(= (travel-time One-Hundred-and-Fifty-Nine One-Hundred-and-Fifty-Eight) 0.5)
	(= (travel-time One-Hundred-and-Sixty One-Hundred-and-Sixty-Three) 0.3)			(= (travel-time One-Hundred-and-Sixty-Three One-Hundred-and-Sixty) 0.3)
	(= (travel-time One-Hundred-and-Ninety-Seven Thirty-Three) 1.6)					(= (travel-time Thirty-Three One-Hundred-and-Ninety-Seven) 1.6)
	(= (travel-time One-Hundred-and-Ninety-Eight One-Hundred-and-Ninety-Five) 1.2)	(= (travel-time One-Hundred-and-Ninety-Five One-Hundred-and-Ninety-Eight) 1.2)
	(= (travel-time One-Hundred-and-Ninety-Five One-Hundred-and-Ninety-Six) 0.3)	(= (travel-time One-Hundred-and-Ninety-Six One-Hundred-and-Ninety-Five) 0.3)
	
	
	(= (travel-time Thirty-Two One-Hundred-and-Ninety-One) 0.5)						(= (travel-time One-Hundred-and-Ninety-One Thirty-Two) 0.5)
	(= (travel-time Thirty-One Two-Hundred-and-Twenty-Nine) 0.5)					(= (travel-time Two-Hundred-and-Twenty-Nine Thirty-One) 0.5)
	(= (travel-time One-Hundred-and-Ninety-One Two-Hundred-and-Twenty-Nine) 0.5)	(= (travel-time Two-Hundred-and-Twenty-Nine One-Hundred-and-Ninety-One) 0.5)
	(= (travel-time Two-Hundred-and-Twenty-Nine Thirty) 0.4)						(= (travel-time Thirty Two-Hundred-and-Twenty-Nine) 0.4)
	(= (travel-time One-Hundred-and-Ninety-One One-Hundred-and-Ninety-Two) 0.4)		(= (travel-time One-Hundred-and-Ninety-Two One-Hundred-and-Ninety-One) 0.4)
	(= (travel-time One-Hundred-and-Ninety-Two Two-Hundred-and-Twenty-Eight) 0.6)	(= (travel-time Two-Hundred-and-Twenty-Eight One-Hundred-and-Ninety-Two) 0.6)
	(= (travel-time Two-Hundred-and-Twenty-Eight Twenty-Nine) 1.2)					(= (travel-time Twenty-Nine Two-Hundred-and-Twenty-Eight) 1.2)
	(= (travel-time Twenty-Eight Twenty-Seven) 0.6)									(= (travel-time Twenty-Seven Twenty-Eight) 0.6)
	(= (travel-time One-Hundred-and-Eighty-Nine Twenty-Seven) 1.6)					(= (travel-time Twenty-Seven One-Hundred-and-Eighty-Nine) 1.6)
	(= (travel-time One-Hundred-and-Eighty-Nine Twenty-Six) 1.4)					(= (travel-time Twenty-Six One-Hundred-and-Eighty-Nine) 1.4)
	(= (travel-time One-Hundred-and-Eighty-Nine One-Hundred-and-Eighty-Eight) 1.5)	(= (travel-time One-Hundred-and-Eighty-Eight One-Hundred-and-Eighty-Nine) 1.5)
	(= (travel-time One-Hundred-and-Eighty-Nine One-Hundred-and-Eighty-Seven) 0.8)	(= (travel-time One-Hundred-and-Eighty-Seven One-Hundred-and-Eighty-Nine) 0.8)
	(= (travel-time One-Hundred-and-Eighty-Seven One-Hundred-and-Eighty-Eight) 0.2)	(= (travel-time One-Hundred-and-Eighty-Eight One-Hundred-and-Eighty-Seven) 0.2)
	(= (travel-time Two-Hundred-and-Twenty-Eight One-Hundred-and-Eighty-Eight) 1)	(= (travel-time One-Hundred-and-Eighty-Eight Two-Hundred-and-Twenty-Eight) 1)
	(= (travel-time One-Hundred-and-Ninety-Three One-Hundred-and-Ninety-Two) 0.2)	(= (travel-time One-Hundred-and-Ninety-Two One-Hundred-and-Ninety-Three) 0.2)
	(= (travel-time One-Hundred-and-Ninety-Three One-Hundred-and-Eighty-Eight) 1)	(= (travel-time One-Hundred-and-Eighty-Eight One-Hundred-and-Ninety-Three) 1)
	(= (travel-time One-Hundred-and-Eighty-Eight One-Hundred-and-Ninety-Four) 1.3) 	(= (travel-time One-Hundred-and-Ninety-Four One-Hundred-and-Eighty-Eight) 1.3)
	(= (travel-time One-Hundred-and-Ninety-Four One-Hundred-and-Ninety-Three) 0.1)	(= (travel-time One-Hundred-and-Ninety-Three One-Hundred-and-Ninety-Four) 0.1)
	(= (travel-time One-Hundred-and-Ninety-Five One-Hundred-and-Ninety-Four) 1.2)	(= (travel-time One-Hundred-and-Ninety-Four One-Hundred-and-Ninety-Five) 1.2)
	(= (travel-time One-Hundred-and-Ninety-Five One-Hundred-and-Eighty-Five) 0.1)	(= (travel-time One-Hundred-and-Eighty-Five One-Hundred-and-Ninety-Five) 0.1)
	(= (travel-time One-Hundred-and-Eighty-Five One-Hundred-and-Eighty-Two) 0.1)	(= (travel-time One-Hundred-and-Eighty-Two One-Hundred-and-Eighty-Five) 0.1)
	(= (travel-time One-Hundred-and-Eighty-Five One-Hundred-and-Eighty-Six) 1.2)	(= (travel-time One-Hundred-and-Eighty-Six One-Hundred-and-Eighty-Five) 1.2)
	(= (travel-time One-Hundred-and-Eighty-Two One-Hundred-and-Eighty-One) 1.2)		(= (travel-time One-Hundred-and-Eighty-One One-Hundred-and-Eighty-Two) 1.2)
	(= (travel-time One-Hundred-and-Ninety-Four One-Hundred-and-Eighty-Six) 0.2)	(= (travel-time One-Hundred-and-Eighty-Six One-Hundred-and-Ninety-Four) 0.2)
	(= (travel-time One-Hundred-and-Eighty-Six One-Hundred-and-Eighty-One) 0.5)		(= (travel-time One-Hundred-and-Eighty-One One-Hundred-and-Eighty-Six) 0.5)
	(= (travel-time One-Hundred-and-Eighty-Two One-Hundred-and-Eighty-Three) 1.3)	(= (travel-time One-Hundred-and-Eighty-Three One-Hundred-and-Eighty-Two) 1.3)
	(= (travel-time One-Hundred-and-Eighty-Five One-Hundred-and-Eighty-Four) 1.1)	(= (travel-time One-Hundred-and-Eighty-Four One-Hundred-and-Eighty-Five) 1.1)
	(= (travel-time One-Hundred-and-Eighty-Three One-Hundred-and-Eighty-Four) 0.2)	(= (travel-time One-Hundred-and-Eighty-Four One-Hundred-and-Eighty-Three) 0.2)
	(= (travel-time One-Hundred-and-Eighty-Four One-Hundred-and-Sixty-Nine) 0.4)	(= (travel-time One-Hundred-and-Sixty-Nine One-Hundred-and-Eighty-Four) 0.4)
	(= (travel-time One-Hundred-and-Eighty-Three One-Hundred-and-Seventy) 0.5)		(= (travel-time One-Hundred-and-Seventy One-Hundred-and-Eighty-Three) 0.5)
	(= (travel-time One-Hundred-and-Sixty-Nine One-Hundred-and-Seventy) 1.3)		(= (travel-time One-Hundred-and-Seventy One-Hundred-and-Sixty-Nine) 1.3)
	(= (travel-time One-Hundred-and-Sixty-Nine One-Hundred-and-Sixty-Five) 0.7)		(= (travel-time One-Hundred-and-Sixty-Five One-Hundred-and-Sixty-Nine) 0.7)
	(= (travel-time One-Hundred-and-Sixty-Five One-Hundred-and-Sixty-Four) 0.3)		(= (travel-time One-Hundred-and-Sixty-Four One-Hundred-and-Sixty-Five) 0.3)
	(= (travel-time One-Hundred-and-Sixty-Five One-Hundred-and-Sixty-Three) 0.5)	(= (travel-time One-Hundred-and-Sixty-Three One-Hundred-and-Sixty-Five) 0.5)
	(= (travel-time One-Hundred-and-Eighty-Two One-Hundred-and-Seventy-Three) 2.2)	(= (travel-time One-Hundred-and-Seventy-Three One-Hundred-and-Eighty-Two) 2.2)
	(= (travel-time One-Hundred-and-Eighty-One One-Hundred-and-Eighty) 1.5)			(= (travel-time One-Hundred-and-Eighty One-Hundred-and-Eighty-One) 1.5)
	(= (travel-time One-Hundred-and-Eighty-Seven One-Hundred-and-Seventy-Nine) 2.3)	(= (travel-time One-Hundred-and-Seventy-Nine One-Hundred-and-Eighty-Seven) 2.3)
	(= (travel-time One-Hundred-and-Eighty One-Hundred-and-Seventy-Nine) 1.1)		(= (travel-time One-Hundred-and-Seventy-Nine One-Hundred-and-Eighty) 1.1)
	(= (travel-time One-Hundred-and-Seventy-Nine Twenty-Five) 2)					(= (travel-time Twenty-Five One-Hundred-and-Seventy-Nine) 2)
	(= (travel-time Twenty-Five Twenty-Four) 0.5)									(= (travel-time Twenty-Four Twenty-Five) 0.5)
	(= (travel-time One-Hundred-and-Sixty-Five One-Hundred-and-Sixty-Six) 0.6)		(= (travel-time One-Hundred-and-Sixty-Six One-Hundred-and-Sixty-Five) 0.6)
	(= (travel-time One-Hundred-and-Sixty-Four One-Hundred-and-Thirty-One) 1)		(= (travel-time One-Hundred-and-Thirty-One One-Hundred-and-Sixty-Four) 1)
	(= (travel-time One-Hundred-and-Sixty-Four One-Hundred-and-Sixty-Six) 1)		(= (travel-time One-Hundred-and-Sixty-Six One-Hundred-and-Sixty-Four) 1)
	
	(= (travel-time Twenty-Two One-Hundred-and-Seventy-Eight) 2.1)					(= (travel-time One-Hundred-and-Seventy-Eight Twenty-Two) 2.1)
	(= (travel-time Twenty-Three One-Hundred-and-Seventy-Eight) 1.8)				(= (travel-time One-Hundred-and-Seventy-Eight Twenty-Three) 1.8)
	(= (travel-time One-Hundred-and-Seventy-Eight One-Hundred-and-Seventy-Seven) 0.3)	(= (travel-time One-Hundred-and-Seventy-Seven One-Hundred-and-Seventy-Eight) 0.3)
	(= (travel-time One-Hundred-and-Seventy-Seven One-Hundred-and-Seventy-Six) 1.8)	(= (travel-time One-Hundred-and-Seventy-Six One-Hundred-and-Seventy-Seven) 1.8)
	(= (travel-time One-Hundred-and-Seventy-Seven One-Hundred-and-Seventy-Nine) 1.5)	(= (travel-time One-Hundred-and-Seventy-Nine One-Hundred-and-Seventy-Seven) 1.5)
	(= (travel-time One-Hundred-and-Eighty One-Hundred-and-Seventy-Six) 1.1)		(= (travel-time One-Hundred-and-Seventy-Six One-Hundred-and-Eighty) 1.1)
	(= (travel-time One-Hundred-and-Seventy-Five One-Hundred-and-Seventy-Six) 1.4)	(= (travel-time One-Hundred-and-Seventy-Six One-Hundred-and-Seventy-Five) 1.4)
	(= (travel-time One-Hundred-and-Seventy-Five One-Hundred-and-Seventy-Four) 0.9)	(= (travel-time One-Hundred-and-Seventy-Four One-Hundred-and-Seventy-Five) 0.9)
	(= (travel-time One-Hundred-and-Seventy-Three One-Hundred-and-Seventy-Four) 0.8)	(= (travel-time One-Hundred-and-Seventy-Four One-Hundred-and-Seventy-Three) 0.8)
	(= (travel-time One-Hundred-and-Seventy-Two One-Hundred-and-Seventy-Four) 0.5)	(= (travel-time One-Hundred-and-Seventy-Four One-Hundred-and-Seventy-Two) 0.5)
	(= (travel-time Twenty-One Two-Hundred-and-Three) 1)							(= (travel-time Two-Hundred-and-Three Twenty-One) 1)
	(= (travel-time Twenty Two-Hundred-and-Three) 1.2)								(= (travel-time Two-Hundred-and-Three Twenty) 1.2)
	(= (travel-time Two-Hundred-and-Three Two-Hundred-and-Two) 0.2)					(= (travel-time Two-Hundred-and-Two Two-Hundred-and-Three) 0.2)
	(= (travel-time Two-Hundred-and-Three Two-Hundred-and-Five) 0.3)				(= (travel-time Two-Hundred-and-Five Two-Hundred-and-Three) 0.3)
	(= (travel-time Two-Hundred-and-Two Two-Hundred-and-Five) 0.2)					(= (travel-time Two-Hundred-and-Five Two-Hundred-and-Two) 0.2)
	(= (travel-time One-Hundred-and-Nine One-Hundred-and-Twenty-Four) 0.7)			(= (travel-time One-Hundred-and-Twenty-Four One-Hundred-and-Nine) 0.7)
	
	(= (travel-time One-Hundred-and-Twelve One-Hundred-and-Thirteen) 1) 			(= (travel-time One-Hundred-and-Thirteen One-Hundred-and-Twelve) 1)
	(= (travel-time One-Hundred-and-Twelve Fifteen) 1.4) 							(= (travel-time Fifteen One-Hundred-and-Twelve) 1.4)
	(= (travel-time One-Hundred-and-Twelve One-Hundred-and-Eleven) 1.6) 			(= (travel-time One-Hundred-and-Eleven One-Hundred-and-Twelve) 1.6)								
	(= (travel-time One-Hundred-and-Thirteen One-Hundred-and-Eleven) 1.3) 			(= (travel-time One-Hundred-and-Eleven One-Hundred-and-Thirteen) 1.3)
	(= (travel-time One-Hundred-and-Eleven One-Hundred-and-Ten) 0.1) 				(= (travel-time One-Hundred-and-Ten One-Hundred-and-Eleven) 0.1)
	(= (travel-time One-Hundred-and-Eleven Fourteen) 1.2) 							(= (travel-time Fourteen One-Hundred-and-Eleven) 1.2)	
	(= (travel-time One-Hundred-and-Thirteen One-Hundred-and-Fourteen) 1.3) 		(= (travel-time One-Hundred-and-Fourteen One-Hundred-and-Thirteen) 1.3)									
	(= (travel-time One-Hundred-and-Eighteen One-Hundred-and-Twenty-Four) 1.6) 		(= (travel-time One-Hundred-and-Twenty-Four One-Hundred-and-Eighteen) 1.6)
	(= (travel-time One-Hundred-and-Nineteen One-Hundred-and-Twenty-One) 1.4) 		(= (travel-time One-Hundred-and-Twenty-One One-Hundred-and-Nineteen) 1.4)				
	(= (travel-time One-Hundred-and-Twenty-One One-Hundred-and-Twenty-Two) 0.7) 	(= (travel-time One-Hundred-and-Twenty-Two One-Hundred-and-Twenty-One) 0.7)										
	(= (travel-time One-Hundred-and-Nineteen One-Hundred-and-Sixteen) 1.4) 			(= (travel-time One-Hundred-and-Sixteen One-Hundred-and-Nineteen) 1.4)
	(= (travel-time One-Hundred-and-Fourteen One-Hundred-and-Fifteen) 0.5)			(= (travel-time One-Hundred-and-Fifteen One-Hundred-and-Fourteen) 0.5)							
	(= (travel-time Sixteen One-Hundred-and-Fifteen) 2)								(= (travel-time One-Hundred-and-Fifteen Sixteen) 2)							
	(= (travel-time One-Hundred-and-Fourteen One-Hundred-and-Eighteen) 0.5)			(= (travel-time One-Hundred-and-Eighteen One-Hundred-and-Fourteen) 0.5)							
	(= (travel-time One-Hundred-and-Eighteen One-Hundred-and-Nineteen) 0.5)			(= (travel-time One-Hundred-and-Nineteen One-Hundred-and-Eighteen) 0.5)							
	(= (travel-time One-Hundred-and-Sixteen One-Hundred-and-Fifteen) 1.3)			(= (travel-time One-Hundred-and-Fifteen One-Hundred-and-Sixteen) 1.3)							
	(= (travel-time One-Hundred-and-Sixteen One-Hundred-and-Seventeen) 1.5)			(= (travel-time One-Hundred-and-Sixteen One-Hundred-and-Seventeen) 1.5)							
	(= (travel-time One-Hundred-and-Seventeen Seventeen) 1.8)						(= (travel-time Seventeen One-Hundred-and-Seventeen) 1.8)							
	(= (travel-time One-Hundred-and-Twenty-One One-Hundred-and-Ninety-Nine) 1.9)	(= (travel-time One-Hundred-and-Ninety-Nine One-Hundred-and-Twenty-One) 1.9)							
	(= (travel-time One-Hundred-and-Twenty One-Hundred-and-Ninety-Nine) 1.2)		(= (travel-time One-Hundred-and-Ninety-Nine One-Hundred-and-Twenty) 1.2)							
	(= (travel-time One-Hundred-and-Twenty Two-Hundred-and-Ten) 1.5)				(= (travel-time Two-Hundred-and-Ten One-Hundred-and-Twenty) 1.5)							
	(= (travel-time One-Hundred-and-Seventeen Two-Hundred-and-Eleven) 1.6) 			(= (travel-time Two-Hundred-and-Eleven One-Hundred-and-Seventeen) 1.6)
	(= (travel-time Two-Hundred-and-Ten Two-Hundred-and-Eleven) 0.6) 				(= (travel-time Two-Hundred-and-Eleven Two-Hundred-and-Ten) 0.6)
	(= (travel-time Two-Hundred-and-Twelve Two-Hundred-and-Eleven) 0.2) 			(= (travel-time Two-Hundred-and-Eleven Two-Hundred-and-Twelve) 0.2)
	(= (travel-time Eighteen Two-Hundred-and-Twelve) 1.3) 							(= (travel-time Two-Hundred-and-Twelve Eighteen) 1.3) 
	(= (travel-time One-Hundred-and-Twenty-Two One-Hundred-and-Seventy-One) 0.9) 	(= (travel-time One-Hundred-and-Seventy-One One-Hundred-and-Twenty-Two) 0.9)										
	(= (travel-time One-Hundred-and-Twenty-Two One-Hundred-and-Seventy-Two) 1) 		(= (travel-time One-Hundred-and-Seventy-Two One-Hundred-and-Twenty-Two) 1)
	(= (travel-time One-Hundred-and-Seventy-Two One-Hundred-and-Seventy-One) 0.8) 	(= (travel-time One-Hundred-and-Seventy-One One-Hundred-and-Seventy-Two) 0.8)
	(= (travel-time One-Hundred-and-Ninety-Nine Two-Hundred) 0.2) 					(= (travel-time Two-Hundred One-Hundred-and-Ninety-Nine) 0.2)
	(= (travel-time Two-Hundred-and-Eight Two-Hundred-and-Ten) 1.2) 				(= (travel-time Two-Hundred-and-Ten Two-Hundred-and-Eight) 1.2)
	(= (travel-time Two-Hundred-and-Twelve Two-Hundred-and-Seven) 1) 				(= (travel-time Two-Hundred-and-Seven Two-Hundred-and-Twelve) 1)
	(= (travel-time Two-Hundred-and-Eight Two-Hundred-and-Seven) 1) 				(= (travel-time Two-Hundred-and-Seven Two-Hundred-and-Eight) 1)
	(= (travel-time Two-Hundred-and-Six Two-Hundred-and-Seven) 0.1) 				(= (travel-time Two-Hundred-and-Seven Two-Hundred-and-Six) 0.1)
	(= (travel-time Two-Hundred-and-Six Nineteen) 0.2) 								(= (travel-time Two-Hundred-and-Six Nineteen) 0.2)
	(= (travel-time Two-Hundred Two-Hundred-and-Eight) 1.2) 						(= (travel-time Two-Hundred-and-Eight Two-Hundred) 1.2)
	(= (travel-time Two-Hundred Two-Hundred-and-Nine) 0.3) 							(= (travel-time Two-Hundred-and-Nine Two-Hundred) 0.3)
	(= (travel-time One-Hundred-and-Seventy-One One-Hundred-and-Seventy-Three) 0.3) (= (travel-time One-Hundred-and-Seventy-Three One-Hundred-and-Seventy-One) 0.3)
	(= (travel-time Two-Hundred-and-Eight Two-Hundred-and-Nine) 0.3) 				(= (travel-time Two-Hundred-and-Nine Two-Hundred-and-Eight) 0.3)
	(= (travel-time Two-Hundred-and-Six Two-Hundred-and-Five) 0.3) 					(= (travel-time Two-Hundred-and-Five Two-Hundred-and-Six) 0.3)
	(= (travel-time Two-Hundred-and-Five Two-Hundred-and-Nine) 0.3) 				(= (travel-time Two-Hundred-and-Nine Two-Hundred-and-Five) 0.3)
	(= (travel-time Two-Hundred Two-Hundred-and-Two) 4.5) 							(= (travel-time Two-Hundred-and-Two Two-Hundred) 4.5))
	
	
(:goal (and 
	(vehicle-at Police-Car-A Two-Hundred-and-Thirty) 								(vehicle-at Police-Car-B Ninety-Eight)
	(vehicle-at Police-Car-C Two-Hundred-and-Twenty-Three)							(vehicle-at Police-Car-D One-Hundred-and-One)
	(vehicle-at Police-Car-E Ninety-Nine) 											(vehicle-at Police-Car-F One-Hundred)
	(treated Casualty-A) 															(treated Casualty-B)
	(treated Casualty-C)															(treated Casualty-D)
	(treated Casualty-E)															
	(blocked Two-Hundred-and-Thirty Two-Hundred-and-Twenty-Three)					(blocked Two-Hundred-and-Thirty Ninety-Eight))
)

(:metric minimize (total-time)))

